import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "hi" | "ta" | "te" | "bn" | "mr" | "kn" | "gu";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

export const languageNames: Record<Language, { label: string; flag: string }> = {
  en: { label: "English", flag: "🇬🇧" },
  hi: { label: "हिंदी", flag: "🇮🇳" },
  ta: { label: "தமிழ்", flag: "🇮🇳" },
  te: { label: "తెలుగు", flag: "🇮🇳" },
  bn: { label: "বাংলা", flag: "🇮🇳" },
  mr: { label: "मराठी", flag: "🇮🇳" },
  kn: { label: "ಕನ್ನಡ", flag: "🇮🇳" },
  gu: { label: "ગુજરાતી", flag: "🇮🇳" },
};

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Header
    "nav.dashboard": "Dashboard",
    "nav.products": "Products",
    "nav.forecasts": "Forecasts",
    "nav.reports": "Reports",
    "nav.simulation": "Simulation",

    // Simulation
    "simulation.title": "OpenEnv Simulation",
    "simulation.subtitle": "Run AI agent simulations on your shop environment",
    "simulation.controlTitle": "Simulation Runner",
    "simulation.controlDesc": "Run the baseline agent across all 3 tasks (Easy, Medium, Hard) with seed=42",
    "simulation.running": "Running...",
    "simulation.runAll": "Run All Tasks",
    "simulation.reset": "Reset",
    "simulation.charts": "Charts",
    "simulation.metrics": "Metrics",
    "simulation.products": "Products",
    "simulation.revenueProfit": "Revenue & Profit",
    "simulation.rewardPerDay": "Reward per Day",
    "simulation.inventoryHealth": "Inventory Health",
    "simulation.forecastAccuracy": "Forecast Accuracy",
    "simulation.totalRevenue": "Total Revenue",
    "simulation.totalProfit": "Total Profit",
    "simulation.totalReward": "Total Reward",
    "simulation.score": "Score",
    "simulation.stockoutDays": "Stockout Events",
    "simulation.overstockUnits": "Overstock Units",
    "simulation.avgAccuracy": "Avg Accuracy",
    "simulation.daysRun": "Days Run",
    "simulation.productPerformance": "Product Performance",
    "simulation.lastDaySnapshot": "Final day snapshot showing demand, sales, and remaining stock",
    "simulation.emptyTitle": "Ready to Simulate",
    "simulation.emptyDesc": "Run the baseline agent to see how it manages pricing, inventory, and forecasting across different difficulty levels.",
    "app.name": "ForecastPro",
    "app.tagline": "Retail Demand Intelligence",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Monitor your inventory and demand predictions",
    "dashboard.totalProducts": "Total Products",
    "dashboard.monthlySales": "Monthly Sales",
    "dashboard.forecastAccuracy": "Forecast Accuracy",
    "dashboard.lowStockAlerts": "Low Stock Alerts",
    "dashboard.activeItems": "Active inventory items",
    "dashboard.revenueMonth": "Revenue this month",
    "dashboard.mlPerformance": "ML model performance",
    "dashboard.needsRestocking": "Items need restocking",

    // Daily Records
    "records.title": "Daily Material Records",
    "records.takePhoto": "Take Photo",
    "records.uploadImage": "Upload Image",
    "records.addNotes": "Add notes about today's materials (optional)...",
    "records.cancel": "Cancel",
    "records.save": "Save Record",
    "records.uploading": "Uploading...",
    "records.recent": "Recent Records",
    "records.loading": "Loading records...",
    "records.empty": "No records yet. Upload your first daily record!",
    "records.preview": "Record Preview",
    "records.previewDesc": "Daily material record photo",
    "records.invalidFile": "Invalid file",
    "records.selectImage": "Please select an image file.",
    "records.fileTooLarge": "File too large",
    "records.maxSize": "Maximum file size is 10MB.",
    "records.notLoggedIn": "Not logged in",
    "records.pleaseLogin": "Please log in to upload records.",
    "records.uploaded": "Record uploaded!",
    "records.uploadedDesc": "Your daily material record has been saved.",
    "records.uploadFailed": "Upload failed",
    "records.deleted": "Record deleted",
    "records.deleteFailed": "Delete failed",

    // Products
    "products.title": "Products",
    "products.subtitle": "Manage your product inventory and categories",
    "products.import": "Import",
    "products.export": "Export",
    "products.addProduct": "Add Product",
    "products.allCategories": "All Categories",
    "products.inStock": "In Stock",
    "products.lowStock": "Low Stock",
    "products.outOfStock": "Out of Stock",
    "products.tableTitle": "Product Inventory & Predictions",
    "products.tableSubtitle": "AI-powered demand forecasts for the next 30 days",
    "products.product": "Product",
    "products.category": "Category",
    "products.currentStock": "Current Stock",
    "products.predictedDemand": "Predicted Demand",
    "products.trend": "Trend",
    "products.confidence": "Confidence",
    "products.status": "Status",
    "products.restockNow": "Restock Now",
    "products.optimal": "Optimal",
    "products.overstock": "Overstock",
    "products.noProducts": "No products match this filter",

    // Insights
    "insights.title": "AI Insights",
    "insights.viewAll": "View All Insights",
    "insights.stockAlert": "Stock Alert",
    "insights.stockAlertDesc": "Rice 5kg bags are predicted to run out in 3 days. Consider restocking 40+ units.",
    "insights.demandSurge": "Demand Surge",
    "insights.demandSurgeDesc": "Organic Milk demand is trending 23% higher than last month. Increase orders.",
    "insights.overstockAlert": "Overstock Alert",
    "insights.overstockAlertDesc": "Sugar inventory exceeds predicted demand. Consider promotional pricing.",

    // Sales Chart
    "chart.title": "Sales & Demand Forecast",
    "chart.subtitle": "Historical data with ML-powered predictions",
    "chart.actualSales": "Actual Sales",
    "chart.predictedDemand": "Predicted Demand",

    // Store Network
    "stores.title": "Store Network",
    "stores.subtitle": "Connect with grocery stores in your area (~5 km radius)",
    "stores.map": "Map",
    "stores.list": "List",
    "stores.registeredStores": "Registered Stores",
    "stores.citiesCovered": "Cities Covered",
    "stores.networkRadius": "Network Radius",
    "stores.storeLocations": "Store Locations",
    "stores.nearbyStores": "Nearby Stores",

    // Forecasts page
    "forecasts.title": "Demand Forecasts",
    "forecasts.subtitle": "AI-powered predictions for inventory planning",
    "forecasts.last30": "Last 30 Days",
    "forecasts.runNew": "Run New Forecast",
    "forecasts.7day": "7-Day Forecast",
    "forecasts.30day": "30-Day Forecast",
    "forecasts.accuracyRate": "Accuracy Rate",
    "forecasts.nextRestock": "Next Restock",
    "forecasts.exportTitle": "Export Forecast Data",
    "forecasts.exportDesc": "Download detailed forecast reports for planning and analysis.",
    "forecasts.exportReport": "Export Report",

    // Run Forecast Dialog
    "forecast.dialogTitle": "Run Demand Forecast",
    "forecast.dialogDesc": "Generate ML-powered demand predictions for your inventory",
    "forecast.complete": "Forecast Complete!",
    "forecast.updated": "Predictions have been updated",
    "forecast.params": "Forecast Parameters",
    "forecast.horizon": "Prediction horizon: 30 days",
    "forecast.model": "Model: Time Series ML",
    "forecast.dataPoints": "Data points: 180 days historical",
    "forecast.allProducts": "Products: All inventory items",
    "forecast.cancel": "Cancel",
    "forecast.start": "Start Forecast",
    "forecast.loading": "Loading historical data...",
    "forecast.preprocessing": "Preprocessing data...",
    "forecast.training": "Training ML model...",
    "forecast.generating": "Generating predictions...",
    "forecast.finalizing": "Finalizing forecast...",
    "forecast.completeToast": "Forecast Complete",
    "forecast.completeDesc": "Demand predictions updated successfully!",

    // Export Dialog
    "export.title": "Export Report",
    "export.desc": "Download your demand forecast report",
    "export.complete": "Export Complete!",
    "export.checkDownloads": "Check your downloads folder",
    "export.summary": "Executive Summary",
    "export.summaryDesc": "High-level overview with key metrics and insights",
    "export.detailed": "Detailed Analysis",
    "export.detailedDesc": "Complete breakdown with product-level predictions",
    "export.raw": "Raw Data Export",
    "export.rawDesc": "CSV export for further analysis in spreadsheets",
    "export.cancel": "Cancel",
    "export.export": "Export Report",
    "export.exporting": "Exporting...",
    "export.exported": "Report Exported",
    "export.exportedDesc": "Your report has been downloaded successfully!",

    // Reports page
    "reports.title": "Reports",
    "reports.subtitle": "Generate and download business reports",
    "reports.schedule": "Schedule Report",
    "reports.generate": "Generate Report",
    "reports.available": "Available Reports",
    "reports.salesPerf": "Sales Performance",
    "reports.salesPerfDesc": "Daily, weekly, and monthly sales analysis with trends",
    "reports.inventoryStatus": "Inventory Status",
    "reports.inventoryStatusDesc": "Current stock levels, reorder points, and turnover rates",
    "reports.demandForecast": "Demand Forecast",
    "reports.demandForecastDesc": "AI-generated predictions for the next 7-30 days",
    "reports.financial": "Financial Summary",
    "reports.financialDesc": "Revenue, costs, and profit margins breakdown",
    "reports.recent": "Recent Reports",
    "reports.recentDesc": "Previously generated reports",

    // Notifications
    "notifs.title": "Notifications",
    "notifs.subtitle": "Stay updated with alerts and insights",
    "notifs.markAllRead": "Mark all read",
    "notifs.empty": "No notifications yet",
    "notifs.lowStock": "Low Stock Alert",
    "notifs.lowStockMsg": "Rice 5kg Bag is running low. Current stock: 30 units.",
    "notifs.forecastUpdated": "Forecast Updated",
    "notifs.forecastUpdatedMsg": "Weekly demand forecast has been updated with 94.2% accuracy.",
    "notifs.newStore": "New Store Registered",
    "notifs.newStoreMsg": "Krishna Groceries has joined your network.",
    "notifs.salesMilestone": "Sales Milestone",
    "notifs.salesMilestoneMsg": "Congratulations! Monthly sales exceeded ₹60,000.",
    "notifs.demandSurge": "Demand Surge",
    "notifs.demandSurgeMsg": "Organic Milk demand trending 23% higher than usual.",
    "notifs.minAgo": "5 min ago",
    "notifs.hourAgo": "1 hour ago",
    "notifs.hoursAgo": "2 hours ago",
    "notifs.dayAgo": "1 day ago",
    "notifs.daysAgo": "2 days ago",

    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage your account and preferences",
    "settings.profile": "Profile",
    "settings.appearance": "Appearance",
    "settings.darkMode": "Dark Mode",
    "settings.darkModeDesc": "Switch to dark theme",
    "settings.notifications": "Notifications",
    "settings.pushNotifs": "Push Notifications",
    "settings.pushNotifsDesc": "Receive browser notifications",
    "settings.emailAlerts": "Email Alerts",
    "settings.emailAlertsDesc": "Daily summary emails",
    "settings.stockAlerts": "Stock Alerts",
    "settings.stockAlertsDesc": "Low inventory warnings",
    "settings.forecastUpdates": "Forecast Updates",
    "settings.forecastUpdatesDesc": "New prediction notifications",
    "settings.privacy": "Privacy & Security",
    "settings.help": "Help & Support",
    "settings.logout": "Log Out",
    "settings.language": "Language",
    "settings.languageDesc": "Choose your preferred language",

    // Footer
    "footer.tagline": "ForecastPro — Intelligent Demand Forecasting for Retail",
    "footer.powered": "Powered by Machine Learning",

    // KPI
    "kpi.totalRevenue": "Total Revenue",
    "kpi.totalOrders": "Total Orders",
    "kpi.profit": "Net Profit",
    "kpi.growth": "Growth Rate",
    "kpi.forecastAccuracy": "Forecast Accuracy",
    "kpi.lowStockAlerts": "Low Stock Alerts",
    "kpi.revenueDesc": "vs last month",
    "kpi.ordersDesc": "vs last month",
    "kpi.profitDesc": "vs last month",
    "kpi.growthDesc": "vs last quarter",
    "kpi.accuracyDesc": "ML model",
    "kpi.alertsDesc": "need restocking",

    // Smart Insights
    "smartInsight.title": "AI Insights & Decision Support",
    "smartInsight.subtitle": "Automated analysis with actionable recommendations",
    "smartInsight.active": "active",
    "smartInsight.stockDepletion": "Stock Depletion Warning",
    "smartInsight.stockDepletionDesc": "Rice 5kg Bag may run out in 3 days at current sales rate. Reorder 50+ units immediately.",
    "smartInsight.salesGrowth": "Sales Growth Detected",
    "smartInsight.salesGrowthDesc": "Organic Milk sales are up 23% this month. Consider increasing price by 5-8% to maximize profit.",
    "smartInsight.lowPerformer": "Low Performing Product",
    "smartInsight.lowPerformerDesc": "Packaged Noodles sales dropped 15% — consider promotional pricing or reducing next order.",
    "smartInsight.bestSeller": "Best Seller Alert",
    "smartInsight.bestSellerDesc": "Rice 5kg Bag is your #1 product with ₹12,400 in sales. Ensure consistent stock levels.",
    "smartInsight.overstockAlert": "Overstock Risk",
    "smartInsight.overstockAlertDesc": "Sugar 1kg inventory exceeds 30-day forecast by 40%. Reduce next order or run a promotion.",
    "smartInsight.restockNow": "Restock Now",
    "smartInsight.reduceInventory": "Reduce Inventory",
    "smartInsight.increasePrice": "Increase Price",
    "smartInsight.viewAll": "View All Insights",
    "smartInsight.actionTaken": "Action Recorded",

    // Charts
    "charts.title": "Advanced Analytics",
    "charts.subtitle": "Interactive data visualization",
    "charts.salesTrend": "Sales Trend",
    "charts.productComparison": "Product Compare",
    "charts.categoryDistribution": "Categories",
    "charts.dailySales": "Daily Sales",
    "charts.movingAverage": "7-Day Moving Avg",
    "charts.predicted": "Predicted",
    "charts.actualSales": "Actual Sales",
    "charts.share": "Share",

    // Inventory Alerts
    "alert.title": "Inventory Alerts",
    "alert.subtitle": "Real-time stock monitoring",
    "alert.depletingIn": "Depleting in",
    "alert.lowStockWarning": "Low stock warning",
    "alert.outOfStock": "Out of stock — reorder immediately",
    "alert.days": "days",
    "alert.stock": "Stock",

    // Expense Tracker
    "expense.title": "Expense Tracker",
    "expense.subtitle": "Track costs and calculate profit",
    "expense.add": "Add",
    "expense.revenue": "Revenue",
    "expense.expenses": "Expenses",
    "expense.netProfit": "Net Profit",
    "expense.margin": "margin",
    "expense.rent": "Rent",
    "expense.rawMaterials": "Raw Materials",
    "expense.salaries": "Salaries",
    "expense.utilities": "Utilities",
    "expense.transport": "Transport",
    "expense.marketing": "Marketing",
    "expense.added": "Expense Added",
    "expense.addTitle": "Add Expense",
    "expense.addDesc": "Record a new business expense",
    "expense.selectCategory": "Select category",
    "expense.amount": "Amount (₹)",

    // Floating Add Sale
    "sale.addSale": "Quick Add Sale",
    "sale.addSaleDesc": "Record a sale quickly",
    "sale.selectProduct": "Select product",
    "sale.quantity": "Quantity",
    "sale.amount": "Amount (₹)",
    "sale.record": "Record Sale",
    "sale.recorded": "Sale Recorded!",

    // Smart Forecast
    "forecast.next7": "Next 7 Days",
    "forecast.next30": "Next 30 Days",
    "forecast.smartTitle": "Smart Forecasting",
    "forecast.smartSubtitle": "Moving averages & trend detection",
    "forecast.vsLastPeriod": "vs last period",
    "forecast.movingAvg": "Moving Avg",
    "forecast.demandIncreasing": "Demand Trending UP ↑",
    "forecast.trendDesc": "Based on 7-day moving average analysis, demand is increasing steadily. Seasonal trends and historical patterns support this trajectory.",

    // AI Chatbot
    "chatbot.title": "AI Assistant",
    "chatbot.subtitle": "Ask about your business",
    "chatbot.welcome": "👋 Hi! I'm your AI business assistant. Ask me about sales, inventory, forecasts, expenses, or anything about your store!",
    "chatbot.placeholder": "Ask me anything...",

    // Setup Wizard
    "setup.welcomeTitle": "Let's set up your shop",
    "setup.shopTypeQuestion": "What type of shop do you run?",
    "setup.grocery": "Grocery",
    "setup.clothing": "Clothing",
    "setup.electronics": "Electronics",
    "setup.pharmacy": "Pharmacy",
    "setup.restaurant": "Restaurant",
    "setup.general": "General Store",
    "setup.customersTitle": "Daily Customers",
    "setup.customersDesc": "How many customers visit per day on average?",
    "setup.avgBillTitle": "Average Bill Value",
    "setup.avgBillDesc": "What's the average amount a customer spends?",
    "setup.estimatedDaily": "Estimated Daily Sales",
    "setup.customers": "customers",
    "setup.perBill": "per bill",
    "setup.back": "Back",
    "setup.next": "Next",
    "setup.getStarted": "Get Started",

    // Quick Daily Input
    "quickInput.title": "Today's Sales",
    "quickInput.subtitle": "Enter in 10 seconds — that's all it takes",
    "quickInput.topProductOptional": "Top-selling product today (optional)",
    "quickInput.prefilled": "Pre-filled from your last entry",
    "quickInput.saveAndSee": "Save & See Insights",
    "quickInput.todaySummary": "Today's Summary",
    "quickInput.todaysSales": "Today's Sales",
    "quickInput.vsAvg": "vs average",
    "quickInput.avgDaily": "Daily Average",
    "quickInput.basedOn": "Based on",
    "quickInput.days": "days",
    "quickInput.updateSales": "Update today's sales",

    // AI Insights
    "insight.aiInsight": "AI Insight",
    "insight.keepTracking": "Keep logging daily sales — after a few days, we'll spot trends and give you smart recommendations.",
    "insight.salesIncreasing": "Your sales are increasing steadily! Consider stocking up on your top products to meet rising demand.",
    "insight.salesDecreasing": "Sales have dipped recently. Try a small promotion or check if a popular product went out of stock.",
    "insight.weekendDemand": "Weekend ahead! Based on patterns, you may see higher demand — make sure your shelves are stocked.",
    "insight.salesSteady": "Sales are steady. Great consistency! Look for opportunities to upsell or introduce a new product.",

    // Common
    "common.storeOwner": "Store Owner",
    "common.something_wrong": "Something went wrong.",
  },
  hi: {
    "nav.dashboard": "डैशबोर्ड",
    "nav.products": "उत्पाद",
    "nav.forecasts": "पूर्वानुमान",
    "nav.reports": "रिपोर्ट",
    "nav.simulation": "सिमुलेशन",
    "simulation.title": "OpenEnv सिमुलेशन",
    "simulation.subtitle": "अपनी दुकान के वातावरण पर AI एजेंट सिमुलेशन चलाएं",
    "simulation.controlTitle": "सिमुलेशन रनर",
    "simulation.controlDesc": "सभी 3 कार्यों (आसान, मध्यम, कठिन) पर बेसलाइन एजेंट चलाएं",
    "simulation.running": "चल रहा है...",
    "simulation.runAll": "सभी कार्य चलाएं",
    "simulation.reset": "रीसेट",
    "simulation.charts": "चार्ट",
    "simulation.metrics": "मेट्रिक्स",
    "simulation.products": "उत्पाद",
    "simulation.revenueProfit": "राजस्व और लाभ",
    "simulation.rewardPerDay": "प्रतिदिन रिवार्ड",
    "simulation.inventoryHealth": "इन्वेंटरी स्वास्थ्य",
    "simulation.forecastAccuracy": "पूर्वानुमान सटीकता",
    "simulation.totalRevenue": "कुल राजस्व",
    "simulation.totalProfit": "कुल लाभ",
    "simulation.totalReward": "कुल रिवार्ड",
    "simulation.score": "स्कोर",
    "simulation.stockoutDays": "स्टॉकआउट घटनाएं",
    "simulation.overstockUnits": "ओवरस्टॉक इकाइयां",
    "simulation.avgAccuracy": "औसत सटीकता",
    "simulation.daysRun": "दिन चले",
    "simulation.productPerformance": "उत्पाद प्रदर्शन",
    "simulation.lastDaySnapshot": "अंतिम दिन का स्नैपशॉट",
    "simulation.emptyTitle": "सिमुलेट करने के लिए तैयार",
    "simulation.emptyDesc": "बेसलाइन एजेंट चलाएं और देखें कि वह मूल्य निर्धारण, इन्वेंटरी और पूर्वानुमान कैसे प्रबंधित करता है।",
    "app.name": "ForecastPro",
    "app.tagline": "खुदरा मांग बुद्धिमत्ता",
    "dashboard.title": "डैशबोर्ड",
    "dashboard.subtitle": "अपनी इन्वेंट्री और मांग पूर्वानुमान की निगरानी करें",
    "dashboard.totalProducts": "कुल उत्पाद",
    "dashboard.monthlySales": "मासिक बिक्री",
    "dashboard.forecastAccuracy": "पूर्वानुमान सटीकता",
    "dashboard.lowStockAlerts": "कम स्टॉक अलर्ट",
    "dashboard.activeItems": "सक्रिय इन्वेंट्री आइटम",
    "dashboard.revenueMonth": "इस महीने का राजस्व",
    "dashboard.mlPerformance": "ML मॉडल प्रदर्शन",
    "dashboard.needsRestocking": "पुनः स्टॉकिंग की आवश्यकता",
    "records.title": "दैनिक सामग्री रिकॉर्ड",
    "records.takePhoto": "फोटो लें",
    "records.uploadImage": "छवि अपलोड करें",
    "records.addNotes": "आज की सामग्री के बारे में नोट्स जोड़ें (वैकल्पिक)...",
    "records.cancel": "रद्द करें",
    "records.save": "रिकॉर्ड सहेजें",
    "records.uploading": "अपलोड हो रहा है...",
    "records.recent": "हाल के रिकॉर्ड",
    "records.loading": "रिकॉर्ड लोड हो रहे हैं...",
    "records.empty": "अभी तक कोई रिकॉर्ड नहीं। अपना पहला दैनिक रिकॉर्ड अपलोड करें!",
    "records.preview": "रिकॉर्ड पूर्वावलोकन",
    "records.previewDesc": "दैनिक सामग्री रिकॉर्ड फोटो",
    "records.invalidFile": "अमान्य फ़ाइल",
    "records.selectImage": "कृपया एक छवि फ़ाइल चुनें।",
    "records.fileTooLarge": "फ़ाइल बहुत बड़ी है",
    "records.maxSize": "अधिकतम फ़ाइल आकार 10MB है।",
    "records.notLoggedIn": "लॉग इन नहीं हैं",
    "records.pleaseLogin": "रिकॉर्ड अपलोड करने के लिए कृपया लॉग इन करें।",
    "records.uploaded": "रिकॉर्ड अपलोड हो गया!",
    "records.uploadedDesc": "आपका दैनिक सामग्री रिकॉर्ड सहेजा गया है।",
    "records.uploadFailed": "अपलोड विफल",
    "records.deleted": "रिकॉर्ड हटाया गया",
    "records.deleteFailed": "हटाना विफल",
    "products.title": "उत्पाद",
    "products.subtitle": "अपनी उत्पाद इन्वेंट्री और श्रेणियाँ प्रबंधित करें",
    "products.import": "आयात",
    "products.export": "निर्यात",
    "products.addProduct": "उत्पाद जोड़ें",
    "products.allCategories": "सभी श्रेणियाँ",
    "products.inStock": "स्टॉक में",
    "products.lowStock": "कम स्टॉक",
    "products.outOfStock": "स्टॉक खत्म",
    "products.tableTitle": "उत्पाद इन्वेंट्री और पूर्वानुमान",
    "products.tableSubtitle": "अगले 30 दिनों के लिए AI-संचालित मांग पूर्वानुमान",
    "products.product": "उत्पाद",
    "products.category": "श्रेणी",
    "products.currentStock": "वर्तमान स्टॉक",
    "products.predictedDemand": "अनुमानित मांग",
    "products.trend": "रुझान",
    "products.confidence": "विश्वसनीयता",
    "products.status": "स्थिति",
    "products.restockNow": "अभी रीस्टॉक करें",
    "products.optimal": "उचित",
    "products.overstock": "अधिक स्टॉक",
    "products.noProducts": "इस फ़िल्टर से कोई उत्पाद मेल नहीं खाता",
    "insights.title": "AI अंतर्दृष्टि",
    "insights.viewAll": "सभी अंतर्दृष्टि देखें",
    "insights.stockAlert": "स्टॉक अलर्ट",
    "insights.stockAlertDesc": "चावल 5 किलो के थैले 3 दिनों में खत्म होने की भविष्यवाणी है। 40+ यूनिट रीस्टॉक करने पर विचार करें।",
    "insights.demandSurge": "मांग में उछाल",
    "insights.demandSurgeDesc": "ऑर्गेनिक दूध की मांग पिछले महीने से 23% अधिक है। ऑर्डर बढ़ाएं।",
    "insights.overstockAlert": "अधिक स्टॉक अलर्ट",
    "insights.overstockAlertDesc": "चीनी की इन्वेंट्री अनुमानित मांग से अधिक है। प्रमोशनल मूल्य निर्धारण पर विचार करें।",
    "chart.title": "बिक्री और मांग पूर्वानुमान",
    "chart.subtitle": "ML-संचालित पूर्वानुमानों के साथ ऐतिहासिक डेटा",
    "chart.actualSales": "वास्तविक बिक्री",
    "chart.predictedDemand": "अनुमानित मांग",
    "stores.title": "स्टोर नेटवर्क",
    "stores.subtitle": "अपने क्षेत्र के किराना स्टोर से जुड़ें (~5 किमी दायरा)",
    "stores.map": "मानचित्र",
    "stores.list": "सूची",
    "stores.registeredStores": "पंजीकृत स्टोर",
    "stores.citiesCovered": "शहर कवर किए गए",
    "stores.networkRadius": "नेटवर्क दायरा",
    "stores.storeLocations": "स्टोर स्थान",
    "stores.nearbyStores": "आस-पास के स्टोर",
    "forecasts.title": "मांग पूर्वानुमान",
    "forecasts.subtitle": "इन्वेंट्री योजना के लिए AI-संचालित पूर्वानुमान",
    "forecasts.last30": "पिछले 30 दिन",
    "forecasts.runNew": "नया पूर्वानुमान चलाएं",
    "forecasts.7day": "7 दिन का पूर्वानुमान",
    "forecasts.30day": "30 दिन का पूर्वानुमान",
    "forecasts.accuracyRate": "सटीकता दर",
    "forecasts.nextRestock": "अगला रीस्टॉक",
    "forecasts.exportTitle": "पूर्वानुमान डेटा निर्यात करें",
    "forecasts.exportDesc": "योजना और विश्लेषण के लिए विस्तृत पूर्वानुमान रिपोर्ट डाउनलोड करें।",
    "forecasts.exportReport": "रिपोर्ट निर्यात करें",
    "forecast.dialogTitle": "मांग पूर्वानुमान चलाएं",
    "forecast.dialogDesc": "अपनी इन्वेंट्री के लिए ML-संचालित मांग पूर्वानुमान उत्पन्न करें",
    "forecast.complete": "पूर्वानुमान पूर्ण!",
    "forecast.updated": "पूर्वानुमान अपडेट हो गए हैं",
    "forecast.params": "पूर्वानुमान पैरामीटर",
    "forecast.horizon": "पूर्वानुमान अवधि: 30 दिन",
    "forecast.model": "मॉडल: टाइम सीरीज ML",
    "forecast.dataPoints": "डेटा पॉइंट: 180 दिन का ऐतिहासिक",
    "forecast.allProducts": "उत्पाद: सभी इन्वेंट्री आइटम",
    "forecast.cancel": "रद्द करें",
    "forecast.start": "पूर्वानुमान शुरू करें",
    "forecast.loading": "ऐतिहासिक डेटा लोड हो रहा है...",
    "forecast.preprocessing": "डेटा प्रीप्रोसेसिंग...",
    "forecast.training": "ML मॉडल प्रशिक्षण...",
    "forecast.generating": "पूर्वानुमान उत्पन्न हो रहे हैं...",
    "forecast.finalizing": "पूर्वानुमान अंतिम रूप दे रहे हैं...",
    "forecast.completeToast": "पूर्वानुमान पूर्ण",
    "forecast.completeDesc": "मांग पूर्वानुमान सफलतापूर्वक अपडेट!",
    "export.title": "रिपोर्ट निर्यात",
    "export.desc": "अपनी मांग पूर्वानुमान रिपोर्ट डाउनलोड करें",
    "export.complete": "निर्यात पूर्ण!",
    "export.checkDownloads": "अपना डाउनलोड फ़ोल्डर जांचें",
    "export.summary": "कार्यकारी सारांश",
    "export.summaryDesc": "प्रमुख मेट्रिक्स और अंतर्दृष्टि का उच्च-स्तरीय अवलोकन",
    "export.detailed": "विस्तृत विश्लेषण",
    "export.detailedDesc": "उत्पाद-स्तरीय पूर्वानुमानों के साथ पूर्ण विश्लेषण",
    "export.raw": "कच्चा डेटा निर्यात",
    "export.rawDesc": "स्प्रेडशीट में विश्लेषण के लिए CSV निर्यात",
    "export.cancel": "रद्द करें",
    "export.export": "रिपोर्ट निर्यात",
    "export.exporting": "निर्यात हो रहा है...",
    "export.exported": "रिपोर्ट निर्यात हो गई",
    "export.exportedDesc": "आपकी रिपोर्ट सफलतापूर्वक डाउनलोड हो गई!",
    "reports.title": "रिपोर्ट",
    "reports.subtitle": "व्यावसायिक रिपोर्ट बनाएं और डाउनलोड करें",
    "reports.schedule": "रिपोर्ट शेड्यूल करें",
    "reports.generate": "रिपोर्ट बनाएं",
    "reports.available": "उपलब्ध रिपोर्ट",
    "reports.salesPerf": "बिक्री प्रदर्शन",
    "reports.salesPerfDesc": "रुझानों के साथ दैनिक, साप्ताहिक और मासिक बिक्री विश्लेषण",
    "reports.inventoryStatus": "इन्वेंट्री स्थिति",
    "reports.inventoryStatusDesc": "वर्तमान स्टॉक स्तर, रीऑर्डर पॉइंट और टर्नओवर दर",
    "reports.demandForecast": "मांग पूर्वानुमान",
    "reports.demandForecastDesc": "अगले 7-30 दिनों के लिए AI-जनित पूर्वानुमान",
    "reports.financial": "वित्तीय सारांश",
    "reports.financialDesc": "राजस्व, लागत और लाभ मार्जिन का विश्लेषण",
    "reports.recent": "हाल की रिपोर्ट",
    "reports.recentDesc": "पहले बनाई गई रिपोर्ट",
    "notifs.title": "सूचनाएँ",
    "notifs.subtitle": "अलर्ट और अंतर्दृष्टि से अपडेट रहें",
    "notifs.markAllRead": "सभी पढ़ा चिह्नित करें",
    "notifs.empty": "अभी कोई सूचना नहीं",
    "notifs.lowStock": "कम स्टॉक अलर्ट",
    "notifs.lowStockMsg": "चावल 5 किलो थैला कम हो रहा है। वर्तमान स्टॉक: 30 यूनिट।",
    "notifs.forecastUpdated": "पूर्वानुमान अपडेट",
    "notifs.forecastUpdatedMsg": "साप्ताहिक मांग पूर्वानुमान 94.2% सटीकता के साथ अपडेट किया गया।",
    "notifs.newStore": "नया स्टोर पंजीकृत",
    "notifs.newStoreMsg": "कृष्णा ग्रोसरीज आपके नेटवर्क में शामिल हो गई।",
    "notifs.salesMilestone": "बिक्री उपलब्धि",
    "notifs.salesMilestoneMsg": "बधाई! मासिक बिक्री ₹60,000 से अधिक हो गई।",
    "notifs.demandSurge": "मांग में उछाल",
    "notifs.demandSurgeMsg": "ऑर्गेनिक दूध की मांग सामान्य से 23% अधिक।",
    "notifs.minAgo": "5 मिनट पहले",
    "notifs.hourAgo": "1 घंटा पहले",
    "notifs.hoursAgo": "2 घंटे पहले",
    "notifs.dayAgo": "1 दिन पहले",
    "notifs.daysAgo": "2 दिन पहले",
    "settings.title": "सेटिंग्स",
    "settings.subtitle": "अपना खाता और प्राथमिकताएँ प्रबंधित करें",
    "settings.profile": "प्रोफ़ाइल",
    "settings.appearance": "दिखावट",
    "settings.darkMode": "डार्क मोड",
    "settings.darkModeDesc": "डार्क थीम पर स्विच करें",
    "settings.notifications": "सूचनाएँ",
    "settings.pushNotifs": "पुश सूचनाएँ",
    "settings.pushNotifsDesc": "ब्राउज़र सूचनाएँ प्राप्त करें",
    "settings.emailAlerts": "ईमेल अलर्ट",
    "settings.emailAlertsDesc": "दैनिक सारांश ईमेल",
    "settings.stockAlerts": "स्टॉक अलर्ट",
    "settings.stockAlertsDesc": "कम इन्वेंट्री चेतावनी",
    "settings.forecastUpdates": "पूर्वानुमान अपडेट",
    "settings.forecastUpdatesDesc": "नई भविष्यवाणी सूचनाएँ",
    "settings.privacy": "गोपनीयता और सुरक्षा",
    "settings.help": "सहायता और समर्थन",
    "settings.logout": "लॉग आउट",
    "settings.language": "भाषा",
    "settings.languageDesc": "अपनी पसंदीदा भाषा चुनें",
    "footer.tagline": "ForecastPro — खुदरा के लिए बुद्धिमान मांग पूर्वानुमान",
    "footer.powered": "मशीन लर्निंग द्वारा संचालित",
    "common.storeOwner": "दुकान मालिक",
    "common.something_wrong": "कुछ गलत हो गया।",
    "setup.welcomeTitle": "अपनी दुकान सेट करें",
    "setup.shopTypeQuestion": "आप किस प्रकार की दुकान चलाते हैं?",
    "setup.grocery": "किराना",
    "setup.clothing": "कपड़े",
    "setup.electronics": "इलेक्ट्रॉनिक्स",
    "setup.pharmacy": "फार्मेसी",
    "setup.restaurant": "रेस्तरां",
    "setup.general": "जनरल स्टोर",
    "setup.customersTitle": "दैनिक ग्राहक",
    "setup.customersDesc": "प्रतिदिन कितने ग्राहक आते हैं?",
    "setup.avgBillTitle": "औसत बिल राशि",
    "setup.avgBillDesc": "एक ग्राहक औसतन कितना खर्च करता है?",
    "setup.estimatedDaily": "अनुमानित दैनिक बिक्री",
    "setup.customers": "ग्राहक",
    "setup.perBill": "प्रति बिल",
    "setup.back": "वापस",
    "setup.next": "अगला",
    "setup.getStarted": "शुरू करें",
    "quickInput.title": "आज की बिक्री",
    "quickInput.subtitle": "10 सेकंड में दर्ज करें — बस इतना ही",
    "quickInput.topProductOptional": "आज का सबसे ज़्यादा बिकने वाला उत्पाद (वैकल्पिक)",
    "quickInput.prefilled": "पिछली एंट्री से पहले से भरा",
    "quickInput.saveAndSee": "सेव करें और इनसाइट देखें",
    "quickInput.todaySummary": "आज का सारांश",
    "quickInput.todaysSales": "आज की बिक्री",
    "quickInput.vsAvg": "औसत से",
    "quickInput.avgDaily": "दैनिक औसत",
    "quickInput.basedOn": "आधारित",
    "quickInput.days": "दिन",
    "quickInput.updateSales": "आज की बिक्री अपडेट करें",
    "insight.aiInsight": "AI इनसाइट",
    "insight.keepTracking": "दैनिक बिक्री लॉग करते रहें — कुछ दिनों बाद हम रुझान बताएंगे।",
    "insight.salesIncreasing": "आपकी बिक्री लगातार बढ़ रही है! अपने टॉप उत्पादों का स्टॉक बढ़ाएं।",
    "insight.salesDecreasing": "बिक्री में गिरावट आई है। छोटा प्रमोशन आज़माएं।",
    "insight.weekendDemand": "वीकेंड आ रहा है! ज़्यादा मांग हो सकती है — स्टॉक तैयार रखें।",
    "insight.salesSteady": "बिक्री स्थिर है। अपसेल या नया उत्पाद आज़माएं।",
    "kpi.totalRevenue": "कुल राजस्व",
    "kpi.totalOrders": "कुल ऑर्डर",
    "kpi.profit": "शुद्ध लाभ",
    "kpi.growth": "विकास दर",
    "kpi.forecastAccuracy": "पूर्वानुमान सटीकता",
    "kpi.lowStockAlerts": "कम स्टॉक अलर्ट",
    "kpi.revenueDesc": "पिछले महीने से",
    "kpi.ordersDesc": "पिछले महीने से",
    "kpi.profitDesc": "पिछले महीने से",
    "kpi.growthDesc": "पिछली तिमाही से",
    "kpi.accuracyDesc": "ML मॉडल",
    "kpi.alertsDesc": "पुनः स्टॉकिंग ज़रूरी",
    "smartInsight.title": "AI अंतर्दृष्टि और निर्णय समर्थन",
    "smartInsight.subtitle": "कार्रवाई योग्य सिफारिशों के साथ स्वचालित विश्लेषण",
    "smartInsight.active": "सक्रिय",
    "smartInsight.stockDepletion": "स्टॉक कमी चेतावनी",
    "smartInsight.stockDepletionDesc": "चावल 5kg बैग वर्तमान बिक्री दर पर 3 दिनों में खत्म हो सकता है। तुरंत 50+ यूनिट ऑर्डर करें।",
    "smartInsight.salesGrowth": "बिक्री वृद्धि",
    "smartInsight.salesGrowthDesc": "ऑर्गेनिक दूध की बिक्री इस महीने 23% बढ़ी। लाभ बढ़ाने के लिए कीमत 5-8% बढ़ाएं।",
    "smartInsight.lowPerformer": "कम प्रदर्शन वाला उत्पाद",
    "smartInsight.lowPerformerDesc": "पैकेज्ड नूडल्स की बिक्री 15% गिरी — प्रमोशनल मूल्य या ऑर्डर कम करें।",
    "smartInsight.bestSeller": "बेस्ट सेलर अलर्ट",
    "smartInsight.bestSellerDesc": "चावल 5kg बैग ₹12,400 बिक्री के साथ #1 उत्पाद है। स्टॉक स्तर बनाए रखें।",
    "smartInsight.overstockAlert": "ओवरस्टॉक जोखिम",
    "smartInsight.overstockAlertDesc": "चीनी 1kg इन्वेंट्री 30-दिन पूर्वानुमान से 40% अधिक है। ऑर्डर कम करें या प्रमोशन चलाएं।",
    "smartInsight.restockNow": "अभी रीस्टॉक करें",
    "smartInsight.reduceInventory": "इन्वेंट्री कम करें",
    "smartInsight.increasePrice": "कीमत बढ़ाएं",
    "smartInsight.viewAll": "सभी अंतर्दृष्टि देखें",
    "smartInsight.actionTaken": "कार्रवाई दर्ज",
    "charts.title": "उन्नत विश्लेषिकी",
    "charts.subtitle": "इंटरैक्टिव डेटा विज़ुअलाइज़ेशन",
    "charts.salesTrend": "बिक्री रुझान",
    "charts.productComparison": "उत्पाद तुलना",
    "charts.categoryDistribution": "श्रेणियां",
    "charts.dailySales": "दैनिक बिक्री",
    "charts.movingAverage": "7-दिन चलती औसत",
    "charts.predicted": "अनुमानित",
    "charts.actualSales": "वास्तविक बिक्री",
    "charts.share": "हिस्सा",
    "alert.title": "इन्वेंट्री अलर्ट",
    "alert.subtitle": "रियल-टाइम स्टॉक निगरानी",
    "alert.depletingIn": "में समाप्त",
    "alert.lowStockWarning": "कम स्टॉक चेतावनी",
    "alert.outOfStock": "स्टॉक खत्म — तुरंत रीऑर्डर करें",
    "alert.days": "दिन",
    "alert.stock": "स्टॉक",
    "expense.title": "खर्च ट्रैकर",
    "expense.subtitle": "लागत ट्रैक करें और लाभ की गणना करें",
    "expense.add": "जोड़ें",
    "expense.revenue": "राजस्व",
    "expense.expenses": "खर्च",
    "expense.netProfit": "शुद्ध लाभ",
    "expense.margin": "मार्जिन",
    "expense.rent": "किराया",
    "expense.rawMaterials": "कच्चा माल",
    "expense.salaries": "वेतन",
    "expense.utilities": "उपयोगिताएं",
    "expense.transport": "परिवहन",
    "expense.marketing": "मार्केटिंग",
    "expense.added": "खर्च जोड़ा गया",
    "expense.addTitle": "खर्च जोड़ें",
    "expense.addDesc": "नया व्यापार खर्च दर्ज करें",
    "expense.selectCategory": "श्रेणी चुनें",
    "expense.amount": "राशि (₹)",
    "sale.addSale": "त्वरित बिक्री जोड़ें",
    "sale.addSaleDesc": "बिक्री जल्दी से दर्ज करें",
    "sale.selectProduct": "उत्पाद चुनें",
    "sale.quantity": "मात्रा",
    "sale.amount": "राशि (₹)",
    "sale.record": "बिक्री दर्ज करें",
    "sale.recorded": "बिक्री दर्ज हो गई!",
    "forecast.next7": "अगले 7 दिन",
    "forecast.next30": "अगले 30 दिन",
    "forecast.smartTitle": "स्मार्ट पूर्वानुमान",
    "forecast.smartSubtitle": "चलती औसत और रुझान पहचान",
    "forecast.vsLastPeriod": "पिछली अवधि से",
    "forecast.movingAvg": "चलती औसत",
    "forecast.demandIncreasing": "मांग बढ़ रही है ↑",
    "forecast.trendDesc": "7-दिन चलती औसत विश्लेषण के आधार पर मांग लगातार बढ़ रही है।",
    "chatbot.title": "AI सहायक",
    "chatbot.subtitle": "अपने व्यापार के बारे में पूछें",
    "chatbot.welcome": "👋 नमस्ते! मैं आपका AI व्यापार सहायक हूं। बिक्री, इन्वेंट्री, पूर्वानुमान, खर्च के बारे में पूछें!",
    "chatbot.placeholder": "कुछ भी पूछें...",
  },
  ta: {
    "nav.dashboard": "டாஷ்போர்டு",
    "nav.products": "பொருட்கள்",
    "nav.forecasts": "முன்கணிப்புகள்",
    "nav.reports": "அறிக்கைகள்",
    "nav.simulation": "உருவகப்படுத்துதல்",
    "app.name": "ForecastPro",
    "app.tagline": "சில்லறை தேவை நுண்ணறிவு",
    "dashboard.title": "டாஷ்போர்டு",
    "dashboard.subtitle": "உங்கள் சரக்கு மற்றும் தேவை முன்கணிப்புகளை கண்காணிக்கவும்",
    "dashboard.totalProducts": "மொத்த பொருட்கள்",
    "dashboard.monthlySales": "மாதாந்திர விற்பனை",
    "dashboard.forecastAccuracy": "முன்கணிப்பு துல்லியம்",
    "dashboard.lowStockAlerts": "குறைந்த சரக்கு எச்சரிக்கைகள்",
    "dashboard.activeItems": "செயலில் உள்ள சரக்கு பொருட்கள்",
    "dashboard.revenueMonth": "இந்த மாத வருவாய்",
    "dashboard.mlPerformance": "ML மாதிரி செயல்திறன்",
    "dashboard.needsRestocking": "மீள்நிரப்பு தேவை",
    "records.title": "தினசரி பொருள் பதிவுகள்",
    "records.takePhoto": "புகைப்படம் எடு",
    "records.uploadImage": "படம் பதிவேற்றம்",
    "records.addNotes": "இன்றைய பொருட்கள் பற்றிய குறிப்புகள் (விருப்பம்)...",
    "records.cancel": "ரத்து",
    "records.save": "பதிவு சேமி",
    "records.uploading": "பதிவேற்றம் செய்யப்படுகிறது...",
    "records.recent": "சமீபத்திய பதிவுகள்",
    "records.loading": "பதிவுகள் ஏற்றப்படுகின்றன...",
    "records.empty": "இதுவரை பதிவுகள் இல்லை. உங்கள் முதல் தினசரி பதிவை பதிவேற்றுங்கள்!",
    "records.preview": "பதிவு முன்னோட்டம்",
    "records.previewDesc": "தினசரி பொருள் பதிவு புகைப்படம்",
    "records.invalidFile": "தவறான கோப்பு",
    "records.selectImage": "தயவுசெய்து ஒரு படக் கோப்பைத் தேர்ந்தெடுக்கவும்.",
    "records.fileTooLarge": "கோப்பு மிகப் பெரியது",
    "records.maxSize": "அதிகபட்ச கோப்பு அளவு 10MB.",
    "records.notLoggedIn": "உள்நுழையவில்லை",
    "records.pleaseLogin": "பதிவுகளை பதிவேற்ற உள்நுழையவும்.",
    "records.uploaded": "பதிவு பதிவேற்றப்பட்டது!",
    "records.uploadedDesc": "உங்கள் தினசரி பொருள் பதிவு சேமிக்கப்பட்டது.",
    "records.uploadFailed": "பதிவேற்றம் தோல்வி",
    "records.deleted": "பதிவு நீக்கப்பட்டது",
    "records.deleteFailed": "நீக்குதல் தோல்வி",
    "products.title": "பொருட்கள்",
    "products.subtitle": "உங்கள் பொருள் சரக்கு மற்றும் வகைகளை நிர்வகிக்கவும்",
    "products.import": "இறக்குமதி",
    "products.export": "ஏற்றுமதி",
    "products.addProduct": "பொருள் சேர்",
    "products.allCategories": "அனைத்து வகைகள்",
    "products.inStock": "சரக்கில்",
    "products.lowStock": "குறைந்த சரக்கு",
    "products.outOfStock": "சரக்கு இல்லை",
    "products.tableTitle": "பொருள் சரக்கு & முன்கணிப்புகள்",
    "products.tableSubtitle": "அடுத்த 30 நாட்களுக்கான AI தேவை முன்கணிப்புகள்",
    "products.product": "பொருள்",
    "products.category": "வகை",
    "products.currentStock": "தற்போதைய சரக்கு",
    "products.predictedDemand": "எதிர்பார்க்கப்படும் தேவை",
    "products.trend": "போக்கு",
    "products.confidence": "நம்பகத்தன்மை",
    "products.status": "நிலை",
    "products.restockNow": "இப்போது மீள்நிரப்பு",
    "products.optimal": "சிறந்த",
    "products.overstock": "அதிக சரக்கு",
    "products.noProducts": "இந்த வடிகட்டியுடன் பொருட்கள் இல்லை",
    "insights.title": "AI நுண்ணறிவுகள்",
    "insights.viewAll": "அனைத்து நுண்ணறிவுகளையும் பார்",
    "insights.stockAlert": "சரக்கு எச்சரிக்கை",
    "insights.stockAlertDesc": "அரிசி 5 கிலோ பைகள் 3 நாட்களில் தீர்ந்துவிடும் என எதிர்பார்க்கப்படுகிறது. 40+ யூனிட்கள் மீள்நிரப்பு செய்யுங்கள்.",
    "insights.demandSurge": "தேவை உயர்வு",
    "insights.demandSurgeDesc": "ஆர்கானிக் பால் தேவை கடந்த மாதத்தை விட 23% அதிகம். ஆர்டர்களை அதிகரிக்கவும்.",
    "insights.overstockAlert": "அதிக சரக்கு எச்சரிக்கை",
    "insights.overstockAlertDesc": "சர்க்கரை சரக்கு எதிர்பார்க்கப்படும் தேவையை விட அதிகம். விலை குறைப்பு செய்யுங்கள்.",
    "chart.title": "விற்பனை & தேவை முன்கணிப்பு",
    "chart.subtitle": "ML முன்கணிப்புகளுடன் வரலாற்று தரவு",
    "chart.actualSales": "உண்மையான விற்பனை",
    "chart.predictedDemand": "எதிர்பார்க்கப்படும் தேவை",
    "stores.title": "கடை வலையமைப்பு",
    "stores.subtitle": "உங்கள் பகுதியில் உள்ள கடைகளுடன் இணையுங்கள் (~5 கிமீ)",
    "stores.map": "வரைபடம்",
    "stores.list": "பட்டியல்",
    "stores.registeredStores": "பதிவு செய்யப்பட்ட கடைகள்",
    "stores.citiesCovered": "உள்ளடக்கிய நகரங்கள்",
    "stores.networkRadius": "வலையமைப்பு ஆரை",
    "stores.storeLocations": "கடை இடங்கள்",
    "stores.nearbyStores": "அருகிலுள்ள கடைகள்",
    "forecasts.title": "தேவை முன்கணிப்புகள்",
    "forecasts.subtitle": "சரக்கு திட்டமிடலுக்கான AI முன்கணிப்புகள்",
    "forecasts.last30": "கடந்த 30 நாட்கள்",
    "forecasts.runNew": "புதிய முன்கணிப்பு",
    "forecasts.7day": "7 நாள் முன்கணிப்பு",
    "forecasts.30day": "30 நாள் முன்கணிப்பு",
    "forecasts.accuracyRate": "துல்லியம் விகிதம்",
    "forecasts.nextRestock": "அடுத்த மீள்நிரப்பு",
    "forecasts.exportTitle": "முன்கணிப்பு தரவை ஏற்றுமதி",
    "forecasts.exportDesc": "விரிவான முன்கணிப்பு அறிக்கைகளை பதிவிறக்கவும்.",
    "forecasts.exportReport": "அறிக்கை ஏற்றுமதி",
    "forecast.dialogTitle": "தேவை முன்கணிப்பு இயக்கு",
    "forecast.dialogDesc": "உங்கள் சரக்குக்கான ML முன்கணிப்புகளை உருவாக்குங்கள்",
    "forecast.complete": "முன்கணிப்பு முடிந்தது!",
    "forecast.updated": "முன்கணிப்புகள் புதுப்பிக்கப்பட்டன",
    "forecast.params": "முன்கணிப்பு அளவுருக்கள்",
    "forecast.horizon": "முன்கணிப்பு காலம்: 30 நாட்கள்",
    "forecast.model": "மாதிரி: நேர வரிசை ML",
    "forecast.dataPoints": "தரவு புள்ளிகள்: 180 நாள் வரலாறு",
    "forecast.allProducts": "பொருட்கள்: அனைத்து சரக்கு",
    "forecast.cancel": "ரத்து",
    "forecast.start": "முன்கணிப்பு தொடங்கு",
    "forecast.loading": "வரலாற்று தரவு ஏற்றப்படுகிறது...",
    "forecast.preprocessing": "தரவு முன்செயலாக்கம்...",
    "forecast.training": "ML மாதிரி பயிற்சி...",
    "forecast.generating": "முன்கணிப்புகள் உருவாக்கப்படுகின்றன...",
    "forecast.finalizing": "முன்கணிப்பு இறுதி செய்யப்படுகிறது...",
    "forecast.completeToast": "முன்கணிப்பு முடிந்தது",
    "forecast.completeDesc": "தேவை முன்கணிப்புகள் வெற்றிகரமாக புதுப்பிக்கப்பட்டன!",
    "export.title": "அறிக்கை ஏற்றுமதி",
    "export.desc": "உங்கள் தேவை முன்கணிப்பு அறிக்கையை பதிவிறக்கவும்",
    "export.complete": "ஏற்றுமதி முடிந்தது!",
    "export.checkDownloads": "உங்கள் பதிவிறக்க கோப்புறையை சரிபாருங்கள்",
    "export.summary": "நிர்வாக சுருக்கம்",
    "export.summaryDesc": "முக்கிய அளவீடுகள் மற்றும் நுண்ணறிவுகளின் மேலோட்டம்",
    "export.detailed": "விரிவான பகுப்பாய்வு",
    "export.detailedDesc": "பொருள் நிலை முன்கணிப்புகளுடன் முழுமையான பகுப்பாய்வு",
    "export.raw": "மூல தரவு ஏற்றுமதி",
    "export.rawDesc": "விரிதாள்களில் பகுப்பாய்வுக்கான CSV ஏற்றுமதி",
    "export.cancel": "ரத்து",
    "export.export": "அறிக்கை ஏற்றுமதி",
    "export.exporting": "ஏற்றுமதி செய்யப்படுகிறது...",
    "export.exported": "அறிக்கை ஏற்றுமதி செய்யப்பட்டது",
    "export.exportedDesc": "உங்கள் அறிக்கை வெற்றிகரமாக பதிவிறக்கப்பட்டது!",
    "reports.title": "அறிக்கைகள்",
    "reports.subtitle": "வணிக அறிக்கைகளை உருவாக்கி பதிவிறக்கவும்",
    "reports.schedule": "அறிக்கை திட்டமிடு",
    "reports.generate": "அறிக்கை உருவாக்கு",
    "reports.available": "கிடைக்கும் அறிக்கைகள்",
    "reports.salesPerf": "விற்பனை செயல்திறன்",
    "reports.salesPerfDesc": "தினசரி, வாராந்திர மற்றும் மாதாந்திர விற்பனை பகுப்பாய்வு",
    "reports.inventoryStatus": "சரக்கு நிலை",
    "reports.inventoryStatusDesc": "தற்போதைய சரக்கு நிலைகள் மற்றும் மீள்நிரப்பு புள்ளிகள்",
    "reports.demandForecast": "தேவை முன்கணிப்பு",
    "reports.demandForecastDesc": "அடுத்த 7-30 நாட்களுக்கான AI முன்கணிப்புகள்",
    "reports.financial": "நிதி சுருக்கம்",
    "reports.financialDesc": "வருவாய், செலவுகள் மற்றும் லாப விகிதம்",
    "reports.recent": "சமீபத்திய அறிக்கைகள்",
    "reports.recentDesc": "முன்பு உருவாக்கிய அறிக்கைகள்",
    "notifs.title": "அறிவிப்புகள்",
    "notifs.subtitle": "எச்சரிக்கைகள் மற்றும் நுண்ணறிவுகளுடன் புதுப்பிக்கவும்",
    "notifs.markAllRead": "அனைத்தையும் படிக்கப்பட்டதாகக் குறி",
    "notifs.empty": "இதுவரை அறிவிப்புகள் இல்லை",
    "notifs.lowStock": "குறைந்த சரக்கு எச்சரிக்கை",
    "notifs.lowStockMsg": "அரிசி 5 கிலோ பை குறைகிறது. தற்போதைய சரக்கு: 30 யூனிட்கள்.",
    "notifs.forecastUpdated": "முன்கணிப்பு புதுப்பிக்கப்பட்டது",
    "notifs.forecastUpdatedMsg": "வாராந்திர தேவை முன்கணிப்பு 94.2% துல்லியத்துடன் புதுப்பிக்கப்பட்டது.",
    "notifs.newStore": "புதிய கடை பதிவு",
    "notifs.newStoreMsg": "கிருஷ்ணா கிராசரீஸ் உங்கள் வலையமைப்பில் சேர்ந்தது.",
    "notifs.salesMilestone": "விற்பனை சாதனை",
    "notifs.salesMilestoneMsg": "வாழ்த்துகள்! மாதாந்திர விற்பனை ₹60,000 தாண்டியது.",
    "notifs.demandSurge": "தேவை உயர்வு",
    "notifs.demandSurgeMsg": "ஆர்கானிக் பால் தேவை வழக்கத்தை விட 23% அதிகம்.",
    "notifs.minAgo": "5 நிமிடங்களுக்கு முன்",
    "notifs.hourAgo": "1 மணி நேரம் முன்",
    "notifs.hoursAgo": "2 மணி நேரம் முன்",
    "notifs.dayAgo": "1 நாளுக்கு முன்",
    "notifs.daysAgo": "2 நாட்களுக்கு முன்",
    "settings.title": "அமைப்புகள்",
    "settings.subtitle": "உங்கள் கணக்கு மற்றும் விருப்பங்களை நிர்வகிக்கவும்",
    "settings.profile": "சுயவிவரம்",
    "settings.appearance": "தோற்றம்",
    "settings.darkMode": "இருண்ட பயன்முறை",
    "settings.darkModeDesc": "இருண்ட தீமுக்கு மாறு",
    "settings.notifications": "அறிவிப்புகள்",
    "settings.pushNotifs": "புஷ் அறிவிப்புகள்",
    "settings.pushNotifsDesc": "உலாவி அறிவிப்புகளைப் பெறு",
    "settings.emailAlerts": "மின்னஞ்சல் எச்சரிக்கைகள்",
    "settings.emailAlertsDesc": "தினசரி சுருக்க மின்னஞ்சல்கள்",
    "settings.stockAlerts": "சரக்கு எச்சரிக்கைகள்",
    "settings.stockAlertsDesc": "குறைந்த சரக்கு எச்சரிக்கைகள்",
    "settings.forecastUpdates": "முன்கணிப்பு புதுப்பிப்புகள்",
    "settings.forecastUpdatesDesc": "புதிய முன்கணிப்பு அறிவிப்புகள்",
    "settings.privacy": "தனியுரிமை & பாதுகாப்பு",
    "settings.help": "உதவி & ஆதரவு",
    "settings.logout": "வெளியேறு",
    "settings.language": "மொழி",
    "settings.languageDesc": "உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்",
    "footer.tagline": "ForecastPro — சில்லறைக்கான புத்திசாலி தேவை முன்கணிப்பு",
    "footer.powered": "இயந்திர கற்றல் மூலம் இயக்கப்படுகிறது",
    "common.storeOwner": "கடை உரிமையாளர்",
    "common.something_wrong": "ஏதோ தவறு ஏற்பட்டது.",
  },
  te: {
    "nav.dashboard": "డాష్‌బోర్డ్",
    "nav.products": "ఉత్పత్తులు",
    "nav.forecasts": "అంచనాలు",
    "nav.reports": "నివేదికలు",
    "nav.simulation": "అనుకరణ",
    "app.name": "ForecastPro",
    "app.tagline": "రిటైల్ డిమాండ్ ఇంటెలిజెన్స్",
    "dashboard.title": "డాష్‌బోర్డ్",
    "dashboard.subtitle": "మీ ఇన్వెంటరీ మరియు డిమాండ్ అంచనాలను పర్యవేక్షించండి",
    "dashboard.totalProducts": "మొత్తం ఉత్పత్తులు",
    "dashboard.monthlySales": "నెలవారీ అమ్మకాలు",
    "dashboard.forecastAccuracy": "అంచనా ఖచ్చితత్వం",
    "dashboard.lowStockAlerts": "తక్కువ స్టాక్ హెచ్చరికలు",
    "dashboard.activeItems": "సక్రియ ఇన్వెంటరీ ఐటమ్‌లు",
    "dashboard.revenueMonth": "ఈ నెల ఆదాయం",
    "dashboard.mlPerformance": "ML మోడల్ పనితీరు",
    "dashboard.needsRestocking": "రీస్టాకింగ్ అవసరం",
    "records.title": "రోజువారీ మెటీరియల్ రికార్డులు",
    "records.takePhoto": "ఫోటో తీయండి",
    "records.uploadImage": "చిత్రం అప్‌లోడ్",
    "records.addNotes": "నేటి మెటీరియల్స్ గురించి నోట్స్ (ఐచ్ఛికం)...",
    "records.cancel": "రద్దు",
    "records.save": "రికార్డు సేవ్",
    "records.uploading": "అప్‌లోడ్ అవుతోంది...",
    "records.recent": "ఇటీవలి రికార్డులు",
    "records.loading": "రికార్డులు లోడ్ అవుతున్నాయి...",
    "records.empty": "ఇంకా రికార్డులు లేవు. మీ మొదటి రోజువారీ రికార్డును అప్‌లోడ్ చేయండి!",
    "records.preview": "రికార్డు ప్రివ్యూ",
    "records.previewDesc": "రోజువారీ మెటీరియల్ రికార్డు ఫోటో",
    "records.invalidFile": "చెల్లని ఫైల్",
    "records.selectImage": "దయచేసి ఒక ఇమేజ్ ఫైల్‌ను ఎంచుకోండి.",
    "records.fileTooLarge": "ఫైల్ చాలా పెద్దది",
    "records.maxSize": "గరిష్ట ఫైల్ పరిమాణం 10MB.",
    "records.notLoggedIn": "లాగిన్ కాలేదు",
    "records.pleaseLogin": "రికార్డులు అప్‌లోడ్ చేయడానికి లాగిన్ చేయండి.",
    "records.uploaded": "రికార్డు అప్‌లోడ్ అయింది!",
    "records.uploadedDesc": "మీ రోజువారీ మెటీరియల్ రికార్డు సేవ్ చేయబడింది.",
    "records.uploadFailed": "అప్‌లోడ్ విఫలమైంది",
    "records.deleted": "రికార్డు తొలగించబడింది",
    "records.deleteFailed": "తొలగింపు విఫలమైంది",
    "products.title": "ఉత్పత్తులు",
    "products.subtitle": "మీ ఉత్పత్తి ఇన్వెంటరీ మరియు వర్గాలను నిర్వహించండి",
    "products.import": "దిగుమతి",
    "products.export": "ఎగుమతి",
    "products.addProduct": "ఉత్పత్తి జోడించు",
    "products.allCategories": "అన్ని వర్గాలు",
    "products.inStock": "స్టాక్‌లో",
    "products.lowStock": "తక్కువ స్టాక్",
    "products.outOfStock": "స్టాక్ లేదు",
    "products.tableTitle": "ఉత్పత్తి ఇన్వెంటరీ & అంచనాలు",
    "products.tableSubtitle": "తర్వాత 30 రోజులకు AI డిమాండ్ అంచనాలు",
    "products.product": "ఉత్పత్తి",
    "products.category": "వర్గం",
    "products.currentStock": "ప్రస్తుత స్టాక్",
    "products.predictedDemand": "అంచనా డిమాండ్",
    "products.trend": "ట్రెండ్",
    "products.confidence": "నమ్మకం",
    "products.status": "స్థితి",
    "products.restockNow": "ఇప్పుడు రీస్టాక్",
    "products.optimal": "సరైనది",
    "products.overstock": "అధిక స్టాక్",
    "products.noProducts": "ఈ ఫిల్టర్‌తో ఉత్పత్తులు లేవు",
    "insights.title": "AI అంతర్దృష్టులు",
    "insights.viewAll": "అన్ని అంతర్దృష్టులు చూడండి",
    "insights.stockAlert": "స్టాక్ హెచ్చరిక",
    "insights.stockAlertDesc": "బియ్యం 5 కిలో బ్యాగులు 3 రోజుల్లో అయిపోతాయని అంచనా. 40+ యూనిట్లు రీస్టాక్ చేయండి.",
    "insights.demandSurge": "డిమాండ్ పెరుగుదల",
    "insights.demandSurgeDesc": "ఆర్గానిక్ పాల డిమాండ్ గత నెలతో పోలిస్తే 23% ఎక్కువ. ఆర్డర్లు పెంచండి.",
    "insights.overstockAlert": "అధిక స్టాక్ హెచ్చరిక",
    "insights.overstockAlertDesc": "చక్కెర ఇన్వెంటరీ అంచనా డిమాండ్ కంటే ఎక్కువ. ప్రమోషనల్ ధరలు పరిగణించండి.",
    "chart.title": "అమ్మకాలు & డిమాండ్ అంచనా",
    "chart.subtitle": "ML అంచనాలతో చారిత్రక డేటా",
    "chart.actualSales": "వాస్తవ అమ్మకాలు",
    "chart.predictedDemand": "అంచనా డిమాండ్",
    "stores.title": "స్టోర్ నెట్‌వర్క్",
    "stores.subtitle": "మీ ప్రాంతంలోని దుకాణాలతో కనెక్ట్ అవ్వండి (~5 కిమీ)",
    "stores.map": "మ్యాప్",
    "stores.list": "జాబితా",
    "stores.registeredStores": "నమోదైన స్టోర్లు",
    "stores.citiesCovered": "కవర్ చేసిన నగరాలు",
    "stores.networkRadius": "నెట్‌వర్క్ వ్యాసార్ధం",
    "stores.storeLocations": "స్టోర్ స్థానాలు",
    "stores.nearbyStores": "సమీపంలోని స్టోర్లు",
    "forecasts.title": "డిమాండ్ అంచనాలు",
    "forecasts.subtitle": "ఇన్వెంటరీ ప్లానింగ్ కోసం AI అంచనాలు",
    "forecasts.last30": "గత 30 రోజులు",
    "forecasts.runNew": "కొత్త అంచనా",
    "forecasts.7day": "7 రోజుల అంచనా",
    "forecasts.30day": "30 రోజుల అంచనా",
    "forecasts.accuracyRate": "ఖచ్చితత్వ రేటు",
    "forecasts.nextRestock": "తర్వాత రీస్టాక్",
    "forecasts.exportTitle": "అంచనా డేటా ఎగుమతి",
    "forecasts.exportDesc": "వివరమైన అంచనా నివేదికలను డౌన్‌లోడ్ చేయండి.",
    "forecasts.exportReport": "నివేదిక ఎగుమతి",
    "forecast.dialogTitle": "డిమాండ్ అంచనా నడపండి",
    "forecast.dialogDesc": "మీ ఇన్వెంటరీ కోసం ML అంచనాలను రూపొందించండి",
    "forecast.complete": "అంచనా పూర్తయింది!",
    "forecast.updated": "అంచనాలు నవీకరించబడ్డాయి",
    "forecast.params": "అంచనా పారామీటర్లు",
    "forecast.horizon": "అంచనా కాలం: 30 రోజులు",
    "forecast.model": "మోడల్: టైమ్ సిరీస్ ML",
    "forecast.dataPoints": "డేటా పాయింట్లు: 180 రోజుల చరిత్ర",
    "forecast.allProducts": "ఉత్పత్తులు: అన్ని ఇన్వెంటరీ",
    "forecast.cancel": "రద్దు",
    "forecast.start": "అంచనా ప్రారంభించు",
    "forecast.loading": "చారిత్రక డేటా లోడ్ అవుతోంది...",
    "forecast.preprocessing": "డేటా ప్రిప్రాసెసింగ్...",
    "forecast.training": "ML మోడల్ శిక్షణ...",
    "forecast.generating": "అంచనాలు రూపొందిస్తోంది...",
    "forecast.finalizing": "అంచనా ఖరారు చేస్తోంది...",
    "forecast.completeToast": "అంచనా పూర్తి",
    "forecast.completeDesc": "డిమాండ్ అంచనాలు విజయవంతంగా నవీకరించబడ్డాయి!",
    "export.title": "నివేదిక ఎగుమతి",
    "export.desc": "మీ డిమాండ్ అంచనా నివేదికను డౌన్‌లోడ్ చేయండి",
    "export.complete": "ఎగుమతి పూర్తి!",
    "export.checkDownloads": "మీ డౌన్‌లోడ్ ఫోల్డర్ చెక్ చేయండి",
    "export.summary": "ఎగ్జిక్యూటివ్ సారాంశం",
    "export.summaryDesc": "ముఖ్య మెట్రిక్స్ మరియు అంతర్దృష్టుల అవలోకనం",
    "export.detailed": "వివరమైన విశ్లేషణ",
    "export.detailedDesc": "ఉత్పత్తి స్థాయి అంచనాలతో పూర్తి విశ్లేషణ",
    "export.raw": "ముడి డేటా ఎగుమతి",
    "export.rawDesc": "స్ప్రెడ్‌షీట్లలో విశ్లేషణ కోసం CSV ఎగుమతి",
    "export.cancel": "రద్దు",
    "export.export": "నివేదిక ఎగుమతి",
    "export.exporting": "ఎగుమతి అవుతోంది...",
    "export.exported": "నివేదిక ఎగుమతి అయింది",
    "export.exportedDesc": "మీ నివేదిక విజయవంతంగా డౌన్‌లోడ్ అయింది!",
    "reports.title": "నివేదికలు",
    "reports.subtitle": "వ్యాపార నివేదికలను రూపొందించి డౌన్‌లోడ్ చేయండి",
    "reports.schedule": "నివేదిక షెడ్యూల్",
    "reports.generate": "నివేదిక రూపొందించు",
    "reports.available": "అందుబాటులో ఉన్న నివేదికలు",
    "reports.salesPerf": "అమ్మకాల పనితీరు",
    "reports.salesPerfDesc": "రోజువారీ, వారవారీ మరియు నెలవారీ అమ్మకాల విశ్లేషణ",
    "reports.inventoryStatus": "ఇన్వెంటరీ స్థితి",
    "reports.inventoryStatusDesc": "ప్రస్తుత స్టాక్ స్థాయిలు మరియు రీఆర్డర్ పాయింట్లు",
    "reports.demandForecast": "డిమాండ్ అంచనా",
    "reports.demandForecastDesc": "తర్వాత 7-30 రోజులకు AI అంచనాలు",
    "reports.financial": "ఆర్థిక సారాంశం",
    "reports.financialDesc": "ఆదాయం, ఖర్చులు మరియు లాభ మార్జిన్లు",
    "reports.recent": "ఇటీవలి నివేదికలు",
    "reports.recentDesc": "ముందుగా రూపొందించిన నివేదికలు",
    "notifs.title": "నోటిఫికేషన్లు",
    "notifs.subtitle": "హెచ్చరికలు మరియు అంతర్దృష్టులతో అప్‌డేట్ అవ్వండి",
    "notifs.markAllRead": "అన్నీ చదివినట్లు గుర్తించు",
    "notifs.empty": "ఇంకా నోటిఫికేషన్లు లేవు",
    "notifs.lowStock": "తక్కువ స్టాక్ హెచ్చరిక",
    "notifs.lowStockMsg": "బియ్యం 5 కిలో బ్యాగ్ తగ్గుతోంది. ప్రస్తుత స్టాక్: 30 యూనిట్లు.",
    "notifs.forecastUpdated": "అంచనా నవీకరణ",
    "notifs.forecastUpdatedMsg": "వారపు డిమాండ్ అంచనా 94.2% ఖచ్చితత్వంతో నవీకరించబడింది.",
    "notifs.newStore": "కొత్త స్టోర్ నమోదు",
    "notifs.newStoreMsg": "కృష్ణ గ్రోసరీస్ మీ నెట్‌వర్క్‌లో చేరింది.",
    "notifs.salesMilestone": "అమ్మకాల మైలురాయి",
    "notifs.salesMilestoneMsg": "అభినందనలు! నెలవారీ అమ్మకాలు ₹60,000 దాటాయి.",
    "notifs.demandSurge": "డిమాండ్ పెరుగుదల",
    "notifs.demandSurgeMsg": "ఆర్గానిక్ పాల డిమాండ్ సాధారణం కంటే 23% ఎక్కువ.",
    "notifs.minAgo": "5 నిమిషాల క్రితం",
    "notifs.hourAgo": "1 గంట క్రితం",
    "notifs.hoursAgo": "2 గంటల క్రితం",
    "notifs.dayAgo": "1 రోజు క్రితం",
    "notifs.daysAgo": "2 రోజుల క్రితం",
    "settings.title": "సెట్టింగ్‌లు",
    "settings.subtitle": "మీ ఖాతా మరియు ప్రాధాన్యతలను నిర్వహించండి",
    "settings.profile": "ప్రొఫైల్",
    "settings.appearance": "రూపం",
    "settings.darkMode": "డార్క్ మోడ్",
    "settings.darkModeDesc": "డార్క్ థీమ్‌కు మారండి",
    "settings.notifications": "నోటిఫికేషన్లు",
    "settings.pushNotifs": "పుష్ నోటిఫికేషన్లు",
    "settings.pushNotifsDesc": "బ్రౌజర్ నోటిఫికేషన్లు అందుకోండి",
    "settings.emailAlerts": "ఇమెయిల్ హెచ్చరికలు",
    "settings.emailAlertsDesc": "రోజువారీ సారాంశ ఇమెయిల్‌లు",
    "settings.stockAlerts": "స్టాక్ హెచ్చరికలు",
    "settings.stockAlertsDesc": "తక్కువ ఇన్వెంటరీ హెచ్చరికలు",
    "settings.forecastUpdates": "అంచనా నవీకరణలు",
    "settings.forecastUpdatesDesc": "కొత్త అంచనా నోటిఫికేషన్లు",
    "settings.privacy": "గోప్యత & భద్రత",
    "settings.help": "సహాయం & మద్దతు",
    "settings.logout": "లాగ్ అవుట్",
    "settings.language": "భాష",
    "settings.languageDesc": "మీ ఇష్టమైన భాషను ఎంచుకోండి",
    "footer.tagline": "ForecastPro — రిటైల్ కోసం తెలివైన డిమాండ్ అంచనా",
    "footer.powered": "మెషీన్ లెర్నింగ్ ద్వారా",
    "common.storeOwner": "దుకాణ యజమాని",
    "common.something_wrong": "ఏదో తప్పు జరిగింది.",
  },
  bn: {
    "nav.dashboard": "ড্যাশবোর্ড",
    "nav.products": "পণ্য",
    "nav.forecasts": "পূর্বাভাস",
    "nav.reports": "রিপোর্ট",
    "nav.simulation": "সিমুলেশন",
    "app.name": "ForecastPro",
    "app.tagline": "খুচরা চাহিদা বুদ্ধিমত্তা",
    "dashboard.title": "ড্যাশবোর্ড",
    "dashboard.subtitle": "আপনার ইনভেন্টরি এবং চাহিদা পূর্বাভাস পর্যবেক্ষণ করুন",
    "dashboard.totalProducts": "মোট পণ্য",
    "dashboard.monthlySales": "মাসিক বিক্রয়",
    "dashboard.forecastAccuracy": "পূর্বাভাস নির্ভুলতা",
    "dashboard.lowStockAlerts": "কম স্টক সতর্কতা",
    "dashboard.activeItems": "সক্রিয় ইনভেন্টরি আইটেম",
    "dashboard.revenueMonth": "এই মাসের আয়",
    "dashboard.mlPerformance": "ML মডেল কর্মক্ষমতা",
    "dashboard.needsRestocking": "পুনঃমজুদ প্রয়োজন",
    "records.title": "দৈনিক উপাদান রেকর্ড",
    "records.takePhoto": "ছবি তুলুন",
    "records.uploadImage": "ছবি আপলোড",
    "records.addNotes": "আজকের উপাদান সম্পর্কে নোট (ঐচ্ছিক)...",
    "records.cancel": "বাতিল",
    "records.save": "রেকর্ড সংরক্ষণ",
    "records.uploading": "আপলোড হচ্ছে...",
    "records.recent": "সাম্প্রতিক রেকর্ড",
    "records.loading": "রেকর্ড লোড হচ্ছে...",
    "records.empty": "এখনো কোনো রেকর্ড নেই। আপনার প্রথম দৈনিক রেকর্ড আপলোড করুন!",
    "records.preview": "রেকর্ড প্রিভিউ",
    "records.previewDesc": "দৈনিক উপাদান রেকর্ড ছবি",
    "records.invalidFile": "অবৈধ ফাইল",
    "records.selectImage": "একটি ছবি ফাইল নির্বাচন করুন।",
    "records.fileTooLarge": "ফাইল খুব বড়",
    "records.maxSize": "সর্বোচ্চ ফাইলের আকার 10MB।",
    "records.notLoggedIn": "লগইন করা হয়নি",
    "records.pleaseLogin": "রেকর্ড আপলোড করতে লগইন করুন।",
    "records.uploaded": "রেকর্ড আপলোড হয়েছে!",
    "records.uploadedDesc": "আপনার দৈনিক উপাদান রেকর্ড সংরক্ষিত হয়েছে।",
    "records.uploadFailed": "আপলোড ব্যর্থ",
    "records.deleted": "রেকর্ড মুছে ফেলা হয়েছে",
    "records.deleteFailed": "মুছে ফেলা ব্যর্থ",
    "products.title": "পণ্য",
    "products.subtitle": "আপনার পণ্য ইনভেন্টরি এবং বিভাগ পরিচালনা করুন",
    "products.import": "আমদানি",
    "products.export": "রপ্তানি",
    "products.addProduct": "পণ্য যোগ করুন",
    "products.allCategories": "সব বিভাগ",
    "products.inStock": "স্টকে আছে",
    "products.lowStock": "কম স্টক",
    "products.outOfStock": "স্টক নেই",
    "products.tableTitle": "পণ্য ইনভেন্টরি ও পূর্বাভাস",
    "products.tableSubtitle": "পরবর্তী 30 দিনের জন্য AI চাহিদা পূর্বাভাস",
    "products.product": "পণ্য",
    "products.category": "বিভাগ",
    "products.currentStock": "বর্তমান স্টক",
    "products.predictedDemand": "অনুমানিত চাহিদা",
    "products.trend": "প্রবণতা",
    "products.confidence": "আস্থা",
    "products.status": "অবস্থা",
    "products.restockNow": "এখনই রিস্টক",
    "products.optimal": "সর্বোত্তম",
    "products.overstock": "অতিরিক্ত স্টক",
    "products.noProducts": "এই ফিল্টারে কোনো পণ্য নেই",
    "insights.title": "AI অন্তর্দৃষ্টি",
    "insights.viewAll": "সব অন্তর্দৃষ্টি দেখুন",
    "insights.stockAlert": "স্টক সতর্কতা",
    "insights.stockAlertDesc": "চাল ৫ কেজি ব্যাগ ৩ দিনে শেষ হবে বলে অনুমান। ৪০+ ইউনিট রিস্টক করুন।",
    "insights.demandSurge": "চাহিদা বৃদ্ধি",
    "insights.demandSurgeDesc": "অর্গানিক দুধের চাহিদা গত মাসের চেয়ে ২৩% বেশি। অর্ডার বাড়ান।",
    "insights.overstockAlert": "অতিরিক্ত স্টক সতর্কতা",
    "insights.overstockAlertDesc": "চিনির ইনভেন্টরি অনুমানিত চাহিদার বেশি। প্রমোশনাল মূল্য বিবেচনা করুন।",
    "chart.title": "বিক্রয় ও চাহিদা পূর্বাভাস",
    "chart.subtitle": "ML পূর্বাভাসের সাথে ঐতিহাসিক ডেটা",
    "chart.actualSales": "প্রকৃত বিক্রয়",
    "chart.predictedDemand": "অনুমানিত চাহিদা",
    "stores.title": "স্টোর নেটওয়ার্ক",
    "stores.subtitle": "আপনার এলাকার দোকানগুলির সাথে সংযুক্ত হন (~৫ কিমি)",
    "stores.map": "মানচিত্র",
    "stores.list": "তালিকা",
    "stores.registeredStores": "নিবন্ধিত স্টোর",
    "stores.citiesCovered": "আওতাভুক্ত শহর",
    "stores.networkRadius": "নেটওয়ার্ক ব্যাসার্ধ",
    "stores.storeLocations": "স্টোর অবস্থান",
    "stores.nearbyStores": "কাছের স্টোর",
    "forecasts.title": "চাহিদা পূর্বাভাস",
    "forecasts.subtitle": "ইনভেন্টরি পরিকল্পনার জন্য AI পূর্বাভাস",
    "forecasts.last30": "গত ৩০ দিন",
    "forecasts.runNew": "নতুন পূর্বাভাস",
    "forecasts.7day": "৭ দিনের পূর্বাভাস",
    "forecasts.30day": "৩০ দিনের পূর্বাভাস",
    "forecasts.accuracyRate": "নির্ভুলতার হার",
    "forecasts.nextRestock": "পরবর্তী রিস্টক",
    "forecasts.exportTitle": "পূর্বাভাস ডেটা রপ্তানি",
    "forecasts.exportDesc": "বিস্তারিত পূর্বাভাস রিপোর্ট ডাউনলোড করুন।",
    "forecasts.exportReport": "রিপোর্ট রপ্তানি",
    "forecast.dialogTitle": "চাহিদা পূর্বাভাস চালান",
    "forecast.dialogDesc": "আপনার ইনভেন্টরির জন্য ML পূর্বাভাস তৈরি করুন",
    "forecast.complete": "পূর্বাভাস সম্পন্ন!",
    "forecast.updated": "পূর্বাভাস আপডেট হয়েছে",
    "forecast.params": "পূর্বাভাস প্যারামিটার",
    "forecast.horizon": "পূর্বাভাস সময়কাল: ৩০ দিন",
    "forecast.model": "মডেল: টাইম সিরিজ ML",
    "forecast.dataPoints": "ডেটা পয়েন্ট: ১৮০ দিনের ইতিহাস",
    "forecast.allProducts": "পণ্য: সকল ইনভেন্টরি",
    "forecast.cancel": "বাতিল",
    "forecast.start": "পূর্বাভাস শুরু",
    "forecast.loading": "ঐতিহাসিক ডেটা লোড হচ্ছে...",
    "forecast.preprocessing": "ডেটা প্রিপ্রসেসিং...",
    "forecast.training": "ML মডেল প্রশিক্ষণ...",
    "forecast.generating": "পূর্বাভাস তৈরি হচ্ছে...",
    "forecast.finalizing": "পূর্বাভাস চূড়ান্ত হচ্ছে...",
    "forecast.completeToast": "পূর্বাভাস সম্পন্ন",
    "forecast.completeDesc": "চাহিদা পূর্বাভাস সফলভাবে আপডেট!",
    "export.title": "রিপোর্ট রপ্তানি",
    "export.desc": "আপনার চাহিদা পূর্বাভাস রিপোর্ট ডাউনলোড করুন",
    "export.complete": "রপ্তানি সম্পন্ন!",
    "export.checkDownloads": "আপনার ডাউনলোড ফোল্ডার দেখুন",
    "export.summary": "কার্যনির্বাহী সারসংক্ষেপ",
    "export.summaryDesc": "মূল মেট্রিক্স এবং অন্তর্দৃষ্টির সংক্ষিপ্ত বিবরণ",
    "export.detailed": "বিস্তারিত বিশ্লেষণ",
    "export.detailedDesc": "পণ্য স্তরের পূর্বাভাসের সাথে সম্পূর্ণ বিশ্লেষণ",
    "export.raw": "কাঁচা ডেটা রপ্তানি",
    "export.rawDesc": "স্প্রেডশীটে বিশ্লেষণের জন্য CSV রপ্তানি",
    "export.cancel": "বাতিল",
    "export.export": "রিপোর্ট রপ্তানি",
    "export.exporting": "রপ্তানি হচ্ছে...",
    "export.exported": "রিপোর্ট রপ্তানি হয়েছে",
    "export.exportedDesc": "আপনার রিপোর্ট সফলভাবে ডাউনলোড হয়েছে!",
    "reports.title": "রিপোর্ট",
    "reports.subtitle": "ব্যবসায়িক রিপোর্ট তৈরি এবং ডাউনলোড করুন",
    "reports.schedule": "রিপোর্ট শিডিউল",
    "reports.generate": "রিপোর্ট তৈরি",
    "reports.available": "উপলব্ধ রিপোর্ট",
    "reports.salesPerf": "বিক্রয় কর্মক্ষমতা",
    "reports.salesPerfDesc": "দৈনিক, সাপ্তাহিক এবং মাসিক বিক্রয় বিশ্লেষণ",
    "reports.inventoryStatus": "ইনভেন্টরি অবস্থা",
    "reports.inventoryStatusDesc": "বর্তমান স্টক স্তর এবং রিঅর্ডার পয়েন্ট",
    "reports.demandForecast": "চাহিদা পূর্বাভাস",
    "reports.demandForecastDesc": "পরবর্তী ৭-৩০ দিনের জন্য AI পূর্বাভাস",
    "reports.financial": "আর্থিক সারসংক্ষেপ",
    "reports.financialDesc": "আয়, ব্যয় এবং লাভ মার্জিন",
    "reports.recent": "সাম্প্রতিক রিপোর্ট",
    "reports.recentDesc": "আগে তৈরি করা রিপোর্ট",
    "notifs.title": "বিজ্ঞপ্তি",
    "notifs.subtitle": "সতর্কতা এবং অন্তর্দৃষ্টি থেকে আপডেট থাকুন",
    "notifs.markAllRead": "সব পড়া হিসেবে চিহ্নিত করুন",
    "notifs.empty": "এখনো কোনো বিজ্ঞপ্তি নেই",
    "notifs.lowStock": "কম স্টক সতর্কতা",
    "notifs.lowStockMsg": "চাল ৫ কেজি ব্যাগ কমে যাচ্ছে। বর্তমান স্টক: ৩০ ইউনিট।",
    "notifs.forecastUpdated": "পূর্বাভাস আপডেট",
    "notifs.forecastUpdatedMsg": "সাপ্তাহিক চাহিদা পূর্বাভাস ৯৪.২% নির্ভুলতায় আপডেট হয়েছে।",
    "notifs.newStore": "নতুন স্টোর নিবন্ধন",
    "notifs.newStoreMsg": "কৃষ্ণা গ্রোসারিজ আপনার নেটওয়ার্কে যোগ দিয়েছে।",
    "notifs.salesMilestone": "বিক্রয় মাইলফলক",
    "notifs.salesMilestoneMsg": "অভিনন্দন! মাসিক বিক্রয় ₹৬০,০০০ ছাড়িয়েছে।",
    "notifs.demandSurge": "চাহিদা বৃদ্ধি",
    "notifs.demandSurgeMsg": "অর্গানিক দুধের চাহিদা স্বাভাবিকের চেয়ে ২৩% বেশি।",
    "notifs.minAgo": "৫ মিনিট আগে",
    "notifs.hourAgo": "১ ঘণ্টা আগে",
    "notifs.hoursAgo": "২ ঘণ্টা আগে",
    "notifs.dayAgo": "১ দিন আগে",
    "notifs.daysAgo": "২ দিন আগে",
    "settings.title": "সেটিংস",
    "settings.subtitle": "আপনার অ্যাকাউন্ট এবং পছন্দ পরিচালনা করুন",
    "settings.profile": "প্রোফাইল",
    "settings.appearance": "চেহারা",
    "settings.darkMode": "ডার্ক মোড",
    "settings.darkModeDesc": "ডার্ক থিমে পরিবর্তন করুন",
    "settings.notifications": "বিজ্ঞপ্তি",
    "settings.pushNotifs": "পুশ বিজ্ঞপ্তি",
    "settings.pushNotifsDesc": "ব্রাউজার বিজ্ঞপ্তি পান",
    "settings.emailAlerts": "ইমেইল সতর্কতা",
    "settings.emailAlertsDesc": "দৈনিক সারসংক্ষেপ ইমেইল",
    "settings.stockAlerts": "স্টক সতর্কতা",
    "settings.stockAlertsDesc": "কম ইনভেন্টরি সতর্কতা",
    "settings.forecastUpdates": "পূর্বাভাস আপডেট",
    "settings.forecastUpdatesDesc": "নতুন পূর্বাভাস বিজ্ঞপ্তি",
    "settings.privacy": "গোপনীয়তা ও নিরাপত্তা",
    "settings.help": "সাহায্য ও সহায়তা",
    "settings.logout": "লগ আউট",
    "settings.language": "ভাষা",
    "settings.languageDesc": "আপনার পছন্দের ভাষা বেছে নিন",
    "footer.tagline": "ForecastPro — খুচরার জন্য বুদ্ধিমান চাহিদা পূর্বাভাস",
    "footer.powered": "মেশিন লার্নিং দ্বারা চালিত",
    "common.storeOwner": "দোকান মালিক",
    "common.something_wrong": "কিছু ভুল হয়েছে।",
  },
  mr: {
    "nav.dashboard": "डॅशबोर्ड",
    "nav.products": "उत्पादने",
    "nav.forecasts": "अंदाज",
    "nav.reports": "अहवाल",
    "nav.simulation": "सिम्युलेशन",
    "app.name": "ForecastPro",
    "app.tagline": "किरकोळ मागणी बुद्धिमत्ता",
    "dashboard.title": "डॅशबोर्ड",
    "dashboard.subtitle": "तुमची इन्व्हेंटरी आणि मागणी अंदाज पहा",
    "dashboard.totalProducts": "एकूण उत्पादने",
    "dashboard.monthlySales": "मासिक विक्री",
    "dashboard.forecastAccuracy": "अंदाज अचूकता",
    "dashboard.lowStockAlerts": "कमी स्टॉक सूचना",
    "dashboard.activeItems": "सक्रिय इन्व्हेंटरी वस्तू",
    "dashboard.revenueMonth": "या महिन्याचा महसूल",
    "dashboard.mlPerformance": "ML मॉडेल कामगिरी",
    "dashboard.needsRestocking": "पुनर्भरणा आवश्यक",
    "records.title": "दैनिक साहित्य नोंदी",
    "records.takePhoto": "फोटो काढा",
    "records.uploadImage": "प्रतिमा अपलोड",
    "records.addNotes": "आजच्या साहित्याबद्दल टिपा (पर्यायी)...",
    "records.cancel": "रद्द करा",
    "records.save": "नोंद जतन करा",
    "records.uploading": "अपलोड होत आहे...",
    "records.recent": "अलीकडच्या नोंदी",
    "records.loading": "नोंदी लोड होत आहेत...",
    "records.empty": "अजून नोंदी नाहीत. तुमची पहिली दैनिक नोंद अपलोड करा!",
    "records.preview": "नोंद पूर्वावलोकन",
    "records.previewDesc": "दैनिक साहित्य नोंद फोटो",
    "records.invalidFile": "अवैध फाइल",
    "records.selectImage": "कृपया एक प्रतिमा फाइल निवडा.",
    "records.fileTooLarge": "फाइल खूप मोठी",
    "records.maxSize": "कमाल फाइल आकार 10MB.",
    "records.notLoggedIn": "लॉग इन नाही",
    "records.pleaseLogin": "नोंदी अपलोड करण्यासाठी लॉग इन करा.",
    "records.uploaded": "नोंद अपलोड झाली!",
    "records.uploadedDesc": "तुमची दैनिक साहित्य नोंद जतन झाली.",
    "records.uploadFailed": "अपलोड अयशस्वी",
    "records.deleted": "नोंद हटवली",
    "records.deleteFailed": "हटवणे अयशस्वी",
    "products.title": "उत्पादने",
    "products.subtitle": "तुमची उत्पाद इन्व्हेंटरी आणि श्रेणी व्यवस्थापित करा",
    "products.import": "आयात",
    "products.export": "निर्यात",
    "products.addProduct": "उत्पाद जोडा",
    "products.allCategories": "सर्व श्रेणी",
    "products.inStock": "स्टॉकमध्ये",
    "products.lowStock": "कमी स्टॉक",
    "products.outOfStock": "स्टॉक नाही",
    "products.tableTitle": "उत्पाद इन्व्हेंटरी आणि अंदाज",
    "products.tableSubtitle": "पुढील 30 दिवसांसाठी AI मागणी अंदाज",
    "products.product": "उत्पाद",
    "products.category": "श्रेणी",
    "products.currentStock": "सध्याचा स्टॉक",
    "products.predictedDemand": "अंदाजित मागणी",
    "products.trend": "ट्रेंड",
    "products.confidence": "विश्वासार्हता",
    "products.status": "स्थिती",
    "products.restockNow": "आता रिस्टॉक करा",
    "products.optimal": "इष्टतम",
    "products.overstock": "अतिरिक्त स्टॉक",
    "products.noProducts": "या फिल्टरमध्ये उत्पादने नाहीत",
    "insights.title": "AI अंतर्दृष्टी",
    "insights.viewAll": "सर्व अंतर्दृष्टी पहा",
    "insights.stockAlert": "स्टॉक सूचना",
    "insights.stockAlertDesc": "तांदूळ 5 किलो पिशव्या 3 दिवसांत संपतील असा अंदाज. 40+ युनिट रिस्टॉक करा.",
    "insights.demandSurge": "मागणी वाढ",
    "insights.demandSurgeDesc": "ऑर्गेनिक दूधाची मागणी गेल्या महिन्यापेक्षा 23% अधिक. ऑर्डर वाढवा.",
    "insights.overstockAlert": "अतिरिक्त स्टॉक सूचना",
    "insights.overstockAlertDesc": "साखरेची इन्व्हेंटरी अंदाजित मागणीपेक्षा अधिक. प्रमोशनल किंमत ठरवा.",
    "chart.title": "विक्री आणि मागणी अंदाज",
    "chart.subtitle": "ML अंदाजांसह ऐतिहासिक डेटा",
    "chart.actualSales": "वास्तविक विक्री",
    "chart.predictedDemand": "अंदाजित मागणी",
    "stores.title": "स्टोअर नेटवर्क",
    "stores.subtitle": "तुमच्या भागातील दुकानांशी जोडा (~5 किमी)",
    "stores.map": "नकाशा",
    "stores.list": "यादी",
    "stores.registeredStores": "नोंदणीकृत स्टोअर",
    "stores.citiesCovered": "समाविष्ट शहरे",
    "stores.networkRadius": "नेटवर्क त्रिज्या",
    "stores.storeLocations": "स्टोअर स्थाने",
    "stores.nearbyStores": "जवळचे स्टोअर",
    "forecasts.title": "मागणी अंदाज",
    "forecasts.subtitle": "इन्व्हेंटरी नियोजनासाठी AI अंदाज",
    "forecasts.last30": "मागील 30 दिवस",
    "forecasts.runNew": "नवीन अंदाज",
    "forecasts.7day": "7 दिवस अंदाज",
    "forecasts.30day": "30 दिवस अंदाज",
    "forecasts.accuracyRate": "अचूकता दर",
    "forecasts.nextRestock": "पुढील रिस्टॉक",
    "forecasts.exportTitle": "अंदाज डेटा निर्यात",
    "forecasts.exportDesc": "सविस्तर अंदाज अहवाल डाउनलोड करा.",
    "forecasts.exportReport": "अहवाल निर्यात",
    "forecast.dialogTitle": "मागणी अंदाज चालवा",
    "forecast.dialogDesc": "तुमच्या इन्व्हेंटरीसाठी ML अंदाज तयार करा",
    "forecast.complete": "अंदाज पूर्ण!",
    "forecast.updated": "अंदाज अद्ययावत झाले",
    "forecast.params": "अंदाज पॅरामीटर",
    "forecast.horizon": "अंदाज कालावधी: 30 दिवस",
    "forecast.model": "मॉडेल: टाइम सिरीज ML",
    "forecast.dataPoints": "डेटा पॉइंट: 180 दिवस इतिहास",
    "forecast.allProducts": "उत्पादने: सर्व इन्व्हेंटरी",
    "forecast.cancel": "रद्द करा",
    "forecast.start": "अंदाज सुरू करा",
    "forecast.loading": "ऐतिहासिक डेटा लोड होत आहे...",
    "forecast.preprocessing": "डेटा प्रीप्रोसेसिंग...",
    "forecast.training": "ML मॉडेल प्रशिक्षण...",
    "forecast.generating": "अंदाज तयार होत आहेत...",
    "forecast.finalizing": "अंदाज अंतिम होत आहे...",
    "forecast.completeToast": "अंदाज पूर्ण",
    "forecast.completeDesc": "मागणी अंदाज यशस्वीरीत्या अद्ययावत!",
    "export.title": "अहवाल निर्यात",
    "export.desc": "तुमचा मागणी अंदाज अहवाल डाउनलोड करा",
    "export.complete": "निर्यात पूर्ण!",
    "export.checkDownloads": "तुमचा डाउनलोड फोल्डर तपासा",
    "export.summary": "कार्यकारी सारांश",
    "export.summaryDesc": "मुख्य मेट्रिक्स आणि अंतर्दृष्टीचा आढावा",
    "export.detailed": "सविस्तर विश्लेषण",
    "export.detailedDesc": "उत्पाद स्तरावरील अंदाजांसह पूर्ण विश्लेषण",
    "export.raw": "कच्चा डेटा निर्यात",
    "export.rawDesc": "स्प्रेडशीटमध्ये विश्लेषणासाठी CSV निर्यात",
    "export.cancel": "रद्द करा",
    "export.export": "अहवाल निर्यात",
    "export.exporting": "निर्यात होत आहे...",
    "export.exported": "अहवाल निर्यात झाला",
    "export.exportedDesc": "तुमचा अहवाल यशस्वीरीत्या डाउनलोड झाला!",
    "reports.title": "अहवाल",
    "reports.subtitle": "व्यवसाय अहवाल तयार करा आणि डाउनलोड करा",
    "reports.schedule": "अहवाल शेड्यूल",
    "reports.generate": "अहवाल तयार करा",
    "reports.available": "उपलब्ध अहवाल",
    "reports.salesPerf": "विक्री कामगिरी",
    "reports.salesPerfDesc": "दैनिक, साप्ताहिक आणि मासिक विक्री विश्लेषण",
    "reports.inventoryStatus": "इन्व्हेंटरी स्थिती",
    "reports.inventoryStatusDesc": "सध्याचे स्टॉक स्तर आणि रिऑर्डर पॉइंट",
    "reports.demandForecast": "मागणी अंदाज",
    "reports.demandForecastDesc": "पुढील 7-30 दिवसांसाठी AI अंदाज",
    "reports.financial": "आर्थिक सारांश",
    "reports.financialDesc": "महसूल, खर्च आणि नफा मार्जिन",
    "reports.recent": "अलीकडचे अहवाल",
    "reports.recentDesc": "आधी तयार केलेले अहवाल",
    "notifs.title": "सूचना",
    "notifs.subtitle": "सूचना आणि अंतर्दृष्टीने अद्ययावत राहा",
    "notifs.markAllRead": "सर्व वाचलेले म्हणून चिन्हांकित करा",
    "notifs.empty": "अजून सूचना नाहीत",
    "notifs.lowStock": "कमी स्टॉक सूचना",
    "notifs.lowStockMsg": "तांदूळ 5 किलो पिशवी कमी होत आहे. सध्याचा स्टॉक: 30 युनिट.",
    "notifs.forecastUpdated": "अंदाज अद्ययावत",
    "notifs.forecastUpdatedMsg": "साप्ताहिक मागणी अंदाज 94.2% अचूकतेने अद्ययावत.",
    "notifs.newStore": "नवीन स्टोअर नोंदणी",
    "notifs.newStoreMsg": "कृष्णा ग्रोसरीज तुमच्या नेटवर्कमध्ये सामील झाली.",
    "notifs.salesMilestone": "विक्री टप्पा",
    "notifs.salesMilestoneMsg": "अभिनंदन! मासिक विक्री ₹60,000 ओलांडली.",
    "notifs.demandSurge": "मागणी वाढ",
    "notifs.demandSurgeMsg": "ऑर्गेनिक दूधाची मागणी नेहमीपेक्षा 23% अधिक.",
    "notifs.minAgo": "5 मिनिटांपूर्वी",
    "notifs.hourAgo": "1 तास पूर्वी",
    "notifs.hoursAgo": "2 तासांपूर्वी",
    "notifs.dayAgo": "1 दिवसापूर्वी",
    "notifs.daysAgo": "2 दिवसांपूर्वी",
    "settings.title": "सेटिंग्ज",
    "settings.subtitle": "तुमचे खाते आणि प्राधान्ये व्यवस्थापित करा",
    "settings.profile": "प्रोफाइल",
    "settings.appearance": "दिसावट",
    "settings.darkMode": "डार्क मोड",
    "settings.darkModeDesc": "डार्क थीमवर स्विच करा",
    "settings.notifications": "सूचना",
    "settings.pushNotifs": "पुश सूचना",
    "settings.pushNotifsDesc": "ब्राउज़र सूचना प्राप्त करा",
    "settings.emailAlerts": "ईमेल सूचना",
    "settings.emailAlertsDesc": "दैनिक सारांश ईमेल",
    "settings.stockAlerts": "स्टॉक सूचना",
    "settings.stockAlertsDesc": "कमी इन्व्हेंटरी सूचना",
    "settings.forecastUpdates": "अंदाज अद्ययावत",
    "settings.forecastUpdatesDesc": "नवीन अंदाज सूचना",
    "settings.privacy": "गोपनीयता आणि सुरक्षा",
    "settings.help": "मदत आणि समर्थन",
    "settings.logout": "लॉग आउट",
    "settings.language": "भाषा",
    "settings.languageDesc": "तुमची आवडती भाषा निवडा",
    "footer.tagline": "ForecastPro — किरकोळ साठी बुद्धिमान मागणी अंदाज",
    "footer.powered": "मशीन लर्निंग द्वारे संचालित",
    "common.storeOwner": "दुकान मालक",
    "common.something_wrong": "काहीतरी चूक झाली.",
  },
  kn: {
    "nav.dashboard": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "nav.products": "ಉತ್ಪನ್ನಗಳು",
    "nav.forecasts": "ಮುನ್ಸೂಚನೆಗಳು",
    "nav.reports": "ವರದಿಗಳು",
    "nav.simulation": "ಅನುಕರಣೆ",
    "app.name": "ForecastPro",
    "app.tagline": "ಚಿಲ್ಲರೆ ಬೇಡಿಕೆ ಬುದ್ಧಿಮತ್ತೆ",
    "dashboard.title": "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    "dashboard.subtitle": "ನಿಮ್ಮ ಸರಕು ಮತ್ತು ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆಗಳನ್ನು ಮೇಲ್ವಿಚಾರಣೆ ಮಾಡಿ",
    "dashboard.totalProducts": "ಒಟ್ಟು ಉತ್ಪನ್ನಗಳು",
    "dashboard.monthlySales": "ಮಾಸಿಕ ಮಾರಾಟ",
    "dashboard.forecastAccuracy": "ಮುನ್ಸೂಚನೆ ನಿಖರತೆ",
    "dashboard.lowStockAlerts": "ಕಡಿಮೆ ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆ",
    "dashboard.activeItems": "ಸಕ್ರಿಯ ಸರಕು ವಸ್ತುಗಳು",
    "dashboard.revenueMonth": "ಈ ತಿಂಗಳ ಆದಾಯ",
    "dashboard.mlPerformance": "ML ಮಾಡೆಲ್ ಕಾರ್ಯಕ್ಷಮತೆ",
    "dashboard.needsRestocking": "ಮರುಸ್ಟಾಕ್ ಅಗತ್ಯ",
    "records.title": "ದೈನಂದಿನ ವಸ್ತು ದಾಖಲೆಗಳು",
    "records.takePhoto": "ಫೋಟೋ ತೆಗೆಯಿರಿ",
    "records.uploadImage": "ಚಿತ್ರ ಅಪ್‌ಲೋಡ್",
    "records.addNotes": "ಇಂದಿನ ವಸ್ತುಗಳ ಬಗ್ಗೆ ಟಿಪ್ಪಣಿಗಳು (ಐಚ್ಛಿಕ)...",
    "records.cancel": "ರದ್ದು",
    "records.save": "ದಾಖಲೆ ಉಳಿಸಿ",
    "records.uploading": "ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "records.recent": "ಇತ್ತೀಚಿನ ದಾಖಲೆಗಳು",
    "records.loading": "ದಾಖಲೆಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ...",
    "records.empty": "ಇನ್ನೂ ದಾಖಲೆಗಳಿಲ್ಲ. ನಿಮ್ಮ ಮೊದಲ ದೈನಂದಿನ ದಾಖಲೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ!",
    "records.preview": "ದಾಖಲೆ ಪೂರ್ವವೀಕ್ಷಣೆ",
    "records.previewDesc": "ದೈನಂದಿನ ವಸ್ತು ದಾಖಲೆ ಫೋಟೋ",
    "records.invalidFile": "ಅಮಾನ್ಯ ಫೈಲ್",
    "records.selectImage": "ದಯವಿಟ್ಟು ಒಂದು ಚಿತ್ರ ಫೈಲ್ ಆಯ್ಕೆಮಾಡಿ.",
    "records.fileTooLarge": "ಫೈಲ್ ತುಂಬಾ ದೊಡ್ಡದು",
    "records.maxSize": "ಗರಿಷ್ಠ ಫೈಲ್ ಗಾತ್ರ 10MB.",
    "records.notLoggedIn": "ಲಾಗಿನ್ ಆಗಿಲ್ಲ",
    "records.pleaseLogin": "ದಾಖಲೆಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ಲಾಗಿನ್ ಮಾಡಿ.",
    "records.uploaded": "ದಾಖಲೆ ಅಪ್‌ಲೋಡ್ ಆಯಿತು!",
    "records.uploadedDesc": "ನಿಮ್ಮ ದೈನಂದಿನ ವಸ್ತು ದಾಖಲೆ ಉಳಿಸಲಾಗಿದೆ.",
    "records.uploadFailed": "ಅಪ್‌ಲೋಡ್ ವಿಫಲ",
    "records.deleted": "ದಾಖಲೆ ಅಳಿಸಲಾಗಿದೆ",
    "records.deleteFailed": "ಅಳಿಸುವಿಕೆ ವಿಫಲ",
    "products.title": "ಉತ್ಪನ್ನಗಳು",
    "products.subtitle": "ನಿಮ್ಮ ಉತ್ಪನ್ನ ಸರಕು ಮತ್ತು ವರ್ಗಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "products.import": "ಆಮದು",
    "products.export": "ರಫ್ತು",
    "products.addProduct": "ಉತ್ಪನ್ನ ಸೇರಿಸಿ",
    "products.allCategories": "ಎಲ್ಲಾ ವರ್ಗಗಳು",
    "products.inStock": "ಸ್ಟಾಕ್‌ನಲ್ಲಿ",
    "products.lowStock": "ಕಡಿಮೆ ಸ್ಟಾಕ್",
    "products.outOfStock": "ಸ್ಟಾಕ್ ಇಲ್ಲ",
    "products.tableTitle": "ಉತ್ಪನ್ನ ಸರಕು ಮತ್ತು ಮುನ್ಸೂಚನೆ",
    "products.tableSubtitle": "ಮುಂದಿನ 30 ದಿನಗಳ AI ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ",
    "products.product": "ಉತ್ಪನ್ನ",
    "products.category": "ವರ್ಗ",
    "products.currentStock": "ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್",
    "products.predictedDemand": "ಅಂದಾಜು ಬೇಡಿಕೆ",
    "products.trend": "ಟ್ರೆಂಡ್",
    "products.confidence": "ನಂಬಿಕೆ",
    "products.status": "ಸ್ಥಿತಿ",
    "products.restockNow": "ಈಗ ರಿಸ್ಟಾಕ್",
    "products.optimal": "ಸೂಕ್ತ",
    "products.overstock": "ಅಧಿಕ ಸ್ಟಾಕ್",
    "products.noProducts": "ಈ ಫಿಲ್ಟರ್‌ನಲ್ಲಿ ಉತ್ಪನ್ನಗಳಿಲ್ಲ",
    "insights.title": "AI ಒಳನೋಟಗಳು",
    "insights.viewAll": "ಎಲ್ಲಾ ಒಳನೋಟಗಳನ್ನು ನೋಡಿ",
    "insights.stockAlert": "ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆ",
    "insights.stockAlertDesc": "ಅಕ್ಕಿ 5 ಕೆಜಿ ಚೀಲಗಳು 3 ದಿನಗಳಲ್ಲಿ ಮುಗಿಯುತ್ತವೆ ಎಂದು ಅಂದಾಜು. 40+ ಘಟಕಗಳನ್ನು ರಿಸ್ಟಾಕ್ ಮಾಡಿ.",
    "insights.demandSurge": "ಬೇಡಿಕೆ ಹೆಚ್ಚಳ",
    "insights.demandSurgeDesc": "ಸಾವಯವ ಹಾಲಿನ ಬೇಡಿಕೆ ಕಳೆದ ತಿಂಗಳಿಗಿಂತ 23% ಹೆಚ್ಚು. ಆರ್ಡರ್‌ಗಳನ್ನು ಹೆಚ್ಚಿಸಿ.",
    "insights.overstockAlert": "ಅಧಿಕ ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆ",
    "insights.overstockAlertDesc": "ಸಕ್ಕರೆ ಸರಕು ಅಂದಾಜು ಬೇಡಿಕೆಗಿಂತ ಹೆಚ್ಚು. ಪ್ರಮೋಷನಲ್ ಬೆಲೆ ಪರಿಗಣಿಸಿ.",
    "chart.title": "ಮಾರಾಟ ಮತ್ತು ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ",
    "chart.subtitle": "ML ಮುನ್ಸೂಚನೆಗಳೊಂದಿಗೆ ಐತಿಹಾಸಿಕ ಡೇಟಾ",
    "chart.actualSales": "ನಿಜವಾದ ಮಾರಾಟ",
    "chart.predictedDemand": "ಅಂದಾಜು ಬೇಡಿಕೆ",
    "stores.title": "ಅಂಗಡಿ ಜಾಲ",
    "stores.subtitle": "ನಿಮ್ಮ ಪ್ರದೇಶದ ಅಂಗಡಿಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ (~5 ಕಿಮೀ)",
    "stores.map": "ನಕ್ಷೆ",
    "stores.list": "ಪಟ್ಟಿ",
    "stores.registeredStores": "ನೋಂದಾಯಿತ ಅಂಗಡಿಗಳು",
    "stores.citiesCovered": "ಒಳಗೊಂಡ ನಗರಗಳು",
    "stores.networkRadius": "ಜಾಲ ತ್ರಿಜ್ಯ",
    "stores.storeLocations": "ಅಂಗಡಿ ಸ್ಥಳಗಳು",
    "stores.nearbyStores": "ಹತ್ತಿರದ ಅಂಗಡಿಗಳು",
    "forecasts.title": "ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆಗಳು",
    "forecasts.subtitle": "ಸರಕು ಯೋಜನೆಗಾಗಿ AI ಮುನ್ಸೂಚನೆಗಳು",
    "forecasts.last30": "ಕಳೆದ 30 ದಿನಗಳು",
    "forecasts.runNew": "ಹೊಸ ಮುನ್ಸೂಚನೆ",
    "forecasts.7day": "7 ದಿನ ಮುನ್ಸೂಚನೆ",
    "forecasts.30day": "30 ದಿನ ಮುನ್ಸೂಚನೆ",
    "forecasts.accuracyRate": "ನಿಖರತೆ ದರ",
    "forecasts.nextRestock": "ಮುಂದಿನ ರಿಸ್ಟಾಕ್",
    "forecasts.exportTitle": "ಮುನ್ಸೂಚನೆ ಡೇಟಾ ರಫ್ತು",
    "forecasts.exportDesc": "ವಿವರವಾದ ಮುನ್ಸೂಚನೆ ವರದಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ.",
    "forecasts.exportReport": "ವರದಿ ರಫ್ತು",
    "forecast.dialogTitle": "ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ ಚಾಲನೆ",
    "forecast.dialogDesc": "ನಿಮ್ಮ ಸರಕಿಗಾಗಿ ML ಮುನ್ಸೂಚನೆಗಳನ್ನು ರಚಿಸಿ",
    "forecast.complete": "ಮುನ್ಸೂಚನೆ ಪೂರ್ಣ!",
    "forecast.updated": "ಮುನ್ಸೂಚನೆಗಳು ನವೀಕರಿಸಲಾಗಿದೆ",
    "forecast.params": "ಮುನ್ಸೂಚನೆ ನಿಯತಾಂಕಗಳು",
    "forecast.horizon": "ಮುನ್ಸೂಚನೆ ಅವಧಿ: 30 ದಿನಗಳು",
    "forecast.model": "ಮಾಡೆಲ್: ಟೈಮ್ ಸೀರೀಸ್ ML",
    "forecast.dataPoints": "ಡೇಟಾ ಪಾಯಿಂಟ್‌ಗಳು: 180 ದಿನಗಳ ಇತಿಹಾಸ",
    "forecast.allProducts": "ಉತ್ಪನ್ನಗಳು: ಎಲ್ಲಾ ಸರಕು",
    "forecast.cancel": "ರದ್ದು",
    "forecast.start": "ಮುನ್ಸೂಚನೆ ಪ್ರಾರಂಭಿಸಿ",
    "forecast.loading": "ಐತಿಹಾಸಿಕ ಡೇಟಾ ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
    "forecast.preprocessing": "ಡೇಟಾ ಪ್ರಿಪ್ರಾಸೆಸಿಂಗ್...",
    "forecast.training": "ML ಮಾಡೆಲ್ ತರಬೇತಿ...",
    "forecast.generating": "ಮುನ್ಸೂಚನೆಗಳು ರಚಿಸಲಾಗುತ್ತಿದೆ...",
    "forecast.finalizing": "ಮುನ್ಸೂಚನೆ ಅಂತಿಮಗೊಳಿಸಲಾಗುತ್ತಿದೆ...",
    "forecast.completeToast": "ಮುನ್ಸೂಚನೆ ಪೂರ್ಣ",
    "forecast.completeDesc": "ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆಗಳು ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!",
    "export.title": "ವರದಿ ರಫ್ತು",
    "export.desc": "ನಿಮ್ಮ ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ ವರದಿಯನ್ನು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    "export.complete": "ರಫ್ತು ಪೂರ್ಣ!",
    "export.checkDownloads": "ನಿಮ್ಮ ಡೌನ್‌ಲೋಡ್ ಫೋಲ್ಡರ್ ಪರಿಶೀಲಿಸಿ",
    "export.summary": "ಕಾರ್ಯನಿರ್ವಾಹಕ ಸಾರಾಂಶ",
    "export.summaryDesc": "ಪ್ರಮುಖ ಮೆಟ್ರಿಕ್ಸ್ ಮತ್ತು ಒಳನೋಟಗಳ ಅವಲೋಕನ",
    "export.detailed": "ವಿವರವಾದ ವಿಶ್ಲೇಷಣೆ",
    "export.detailedDesc": "ಉತ್ಪನ್ನ ಮಟ್ಟದ ಮುನ್ಸೂಚನೆಗಳೊಂದಿಗೆ ಪೂರ್ಣ ವಿಶ್ಲೇಷಣೆ",
    "export.raw": "ಕಚ್ಚಾ ಡೇಟಾ ರಫ್ತು",
    "export.rawDesc": "ಸ್ಪ್ರೆಡ್‌ಶೀಟ್‌ಗಳಲ್ಲಿ ವಿಶ್ಲೇಷಣೆಗಾಗಿ CSV ರಫ್ತು",
    "export.cancel": "ರದ್ದು",
    "export.export": "ವರದಿ ರಫ್ತು",
    "export.exporting": "ರಫ್ತಾಗುತ್ತಿದೆ...",
    "export.exported": "ವರದಿ ರಫ್ತಾಗಿದೆ",
    "export.exportedDesc": "ನಿಮ್ಮ ವರದಿ ಯಶಸ್ವಿಯಾಗಿ ಡೌನ್‌ಲೋಡ್ ಆಗಿದೆ!",
    "reports.title": "ವರದಿಗಳು",
    "reports.subtitle": "ವ್ಯಾಪಾರ ವರದಿಗಳನ್ನು ರಚಿಸಿ ಮತ್ತು ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    "reports.schedule": "ವರದಿ ಶೆಡ್ಯೂಲ್",
    "reports.generate": "ವರದಿ ರಚಿಸಿ",
    "reports.available": "ಲಭ್ಯವಿರುವ ವರದಿಗಳು",
    "reports.salesPerf": "ಮಾರಾಟ ಕಾರ್ಯಕ್ಷಮತೆ",
    "reports.salesPerfDesc": "ದೈನಂದಿನ, ಸಾಪ್ತಾಹಿಕ ಮತ್ತು ಮಾಸಿಕ ಮಾರಾಟ ವಿಶ್ಲೇಷಣೆ",
    "reports.inventoryStatus": "ಸರಕು ಸ್ಥಿತಿ",
    "reports.inventoryStatusDesc": "ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್ ಮಟ್ಟಗಳು ಮತ್ತು ರಿಆರ್ಡರ್ ಪಾಯಿಂಟ್‌ಗಳು",
    "reports.demandForecast": "ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ",
    "reports.demandForecastDesc": "ಮುಂದಿನ 7-30 ದಿನಗಳ AI ಮುನ್ಸೂಚನೆಗಳು",
    "reports.financial": "ಆರ್ಥಿಕ ಸಾರಾಂಶ",
    "reports.financialDesc": "ಆದಾಯ, ವೆಚ್ಚಗಳು ಮತ್ತು ಲಾಭ ಮಾರ್ಜಿನ್‌ಗಳು",
    "reports.recent": "ಇತ್ತೀಚಿನ ವರದಿಗಳು",
    "reports.recentDesc": "ಹಿಂದೆ ರಚಿಸಿದ ವರದಿಗಳು",
    "notifs.title": "ಅಧಿಸೂಚನೆಗಳು",
    "notifs.subtitle": "ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಒಳನೋಟಗಳೊಂದಿಗೆ ನವೀಕೃತರಾಗಿ",
    "notifs.markAllRead": "ಎಲ್ಲವನ್ನೂ ಓದಿದೆ ಎಂದು ಗುರುತಿಸಿ",
    "notifs.empty": "ಇನ್ನೂ ಅಧಿಸೂಚನೆಗಳಿಲ್ಲ",
    "notifs.lowStock": "ಕಡಿಮೆ ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆ",
    "notifs.lowStockMsg": "ಅಕ್ಕಿ 5 ಕೆಜಿ ಬ್ಯಾಗ್ ಕಡಿಮೆಯಾಗುತ್ತಿದೆ. ಪ್ರಸ್ತುತ ಸ್ಟಾಕ್: 30 ಘಟಕಗಳು.",
    "notifs.forecastUpdated": "ಮುನ್ಸೂಚನೆ ನವೀಕರಣ",
    "notifs.forecastUpdatedMsg": "ಸಾಪ್ತಾಹಿಕ ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ 94.2% ನಿಖರತೆಯೊಂದಿಗೆ ನವೀಕರಿಸಲಾಗಿದೆ.",
    "notifs.newStore": "ಹೊಸ ಅಂಗಡಿ ನೋಂದಣಿ",
    "notifs.newStoreMsg": "ಕೃಷ್ಣ ಗ್ರೋಸರೀಸ್ ನಿಮ್ಮ ಜಾಲಕ್ಕೆ ಸೇರಿದೆ.",
    "notifs.salesMilestone": "ಮಾರಾಟ ಮೈಲಿಗಲ್ಲು",
    "notifs.salesMilestoneMsg": "ಅಭಿನಂದನೆ! ಮಾಸಿಕ ಮಾರಾಟ ₹60,000 ಮೀರಿದೆ.",
    "notifs.demandSurge": "ಬೇಡಿಕೆ ಹೆಚ್ಚಳ",
    "notifs.demandSurgeMsg": "ಸಾವಯವ ಹಾಲಿನ ಬೇಡಿಕೆ ಸಾಮಾನ್ಯಕ್ಕಿಂತ 23% ಹೆಚ್ಚು.",
    "notifs.minAgo": "5 ನಿಮಿಷಗಳ ಹಿಂದೆ",
    "notifs.hourAgo": "1 ಗಂಟೆ ಹಿಂದೆ",
    "notifs.hoursAgo": "2 ಗಂಟೆಗಳ ಹಿಂದೆ",
    "notifs.dayAgo": "1 ದಿನದ ಹಿಂದೆ",
    "notifs.daysAgo": "2 ದಿನಗಳ ಹಿಂದೆ",
    "settings.title": "ಸೆಟ್ಟಿಂಗ್‌ಗಳು",
    "settings.subtitle": "ನಿಮ್ಮ ಖಾತೆ ಮತ್ತು ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ",
    "settings.profile": "ಪ್ರೊಫೈಲ್",
    "settings.appearance": "ಗೋಚರತೆ",
    "settings.darkMode": "ಡಾರ್ಕ್ ಮೋಡ್",
    "settings.darkModeDesc": "ಡಾರ್ಕ್ ಥೀಮ್‌ಗೆ ಬದಲಿಸಿ",
    "settings.notifications": "ಅಧಿಸೂಚನೆಗಳು",
    "settings.pushNotifs": "ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು",
    "settings.pushNotifsDesc": "ಬ್ರೌಸರ್ ಅಧಿಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ",
    "settings.emailAlerts": "ಇಮೇಲ್ ಎಚ್ಚರಿಕೆಗಳು",
    "settings.emailAlertsDesc": "ದೈನಂದಿನ ಸಾರಾಂಶ ಇಮೇಲ್‌ಗಳು",
    "settings.stockAlerts": "ಸ್ಟಾಕ್ ಎಚ್ಚರಿಕೆಗಳು",
    "settings.stockAlertsDesc": "ಕಡಿಮೆ ಸರಕು ಎಚ್ಚರಿಕೆಗಳು",
    "settings.forecastUpdates": "ಮುನ್ಸೂಚನೆ ನವೀಕರಣಗಳು",
    "settings.forecastUpdatesDesc": "ಹೊಸ ಮುನ್ಸೂಚನೆ ಅಧಿಸೂಚನೆಗಳು",
    "settings.privacy": "ಗೌಪ್ಯತೆ & ಭದ್ರತೆ",
    "settings.help": "ಸಹಾಯ & ಬೆಂಬಲ",
    "settings.logout": "ಲಾಗ್ ಔಟ್",
    "settings.language": "ಭಾಷೆ",
    "settings.languageDesc": "ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
    "footer.tagline": "ForecastPro — ಚಿಲ್ಲರೆಗಾಗಿ ಬುದ್ಧಿವಂತ ಬೇಡಿಕೆ ಮುನ್ಸೂಚನೆ",
    "footer.powered": "ಯಂತ್ರ ಕಲಿಕೆಯಿಂದ ಚಾಲಿತ",
    "common.storeOwner": "ಅಂಗಡಿ ಮಾಲೀಕ",
    "common.something_wrong": "ಏನೋ ತಪ್ಪಾಗಿದೆ.",
  },
  gu: {
    "nav.dashboard": "ડેશબોર્ડ",
    "nav.products": "ઉત્પાદનો",
    "nav.forecasts": "આગાહીઓ",
    "nav.reports": "અહેવાલો",
    "nav.simulation": "સિમ્યુલેશન",
    "app.name": "ForecastPro",
    "app.tagline": "છૂટક માંગ બુદ્ધિમત્તા",
    "dashboard.title": "ડેશબોર્ડ",
    "dashboard.subtitle": "તમારી ઇન્વેન્ટરી અને માંગ આગાહીનું નિરીક્ષણ કરો",
    "dashboard.totalProducts": "કુલ ઉત્પાદનો",
    "dashboard.monthlySales": "માસિક વેચાણ",
    "dashboard.forecastAccuracy": "આગાહી ચોકસાઈ",
    "dashboard.lowStockAlerts": "ઓછો સ્ટોક ચેતવણી",
    "dashboard.activeItems": "સક્રિય ઇન્વેન્ટરી આઇટમ",
    "dashboard.revenueMonth": "આ મહિનાની આવક",
    "dashboard.mlPerformance": "ML મોડેલ પ્રદર્શન",
    "dashboard.needsRestocking": "પુનઃસ્ટોકિંગ જરૂરી",
    "records.title": "દૈનિક સામગ્રી રેકોર્ડ",
    "records.takePhoto": "ફોટો લો",
    "records.uploadImage": "છબી અપલોડ",
    "records.addNotes": "આજની સામગ્રી વિશે નોંધો (વૈકલ્પિક)...",
    "records.cancel": "રદ કરો",
    "records.save": "રેકોર્ડ સાચવો",
    "records.uploading": "અપલોડ થઈ રહ્યું છે...",
    "records.recent": "તાજેતરના રેકોર્ડ",
    "records.loading": "રેકોર્ડ લોડ થઈ રહ્યા છે...",
    "records.empty": "હજુ સુધી કોઈ રેકોર્ડ નથી. તમારો પ્રથમ દૈનિક રેકોર્ડ અપલોડ કરો!",
    "records.preview": "રેકોર્ડ પૂર્વાવલોકન",
    "records.previewDesc": "દૈનિક સામગ્રી રેકોર્ડ ફોટો",
    "records.invalidFile": "અમાન્ય ફાઇલ",
    "records.selectImage": "કૃપા કરીને એક છબી ફાઇલ પસંદ કરો.",
    "records.fileTooLarge": "ફાઇલ ખૂબ મોટી",
    "records.maxSize": "મહત્તમ ફાઇલ કદ 10MB.",
    "records.notLoggedIn": "લોગિન નથી",
    "records.pleaseLogin": "રેકોર્ડ અપલોડ કરવા લોગિન કરો.",
    "records.uploaded": "રેકોર્ડ અપલોડ થયો!",
    "records.uploadedDesc": "તમારો દૈનિક સામગ્રી રેકોર્ડ સાચવવામાં આવ્યો.",
    "records.uploadFailed": "અપલોડ નિષ્ફળ",
    "records.deleted": "રેકોર્ડ કાઢી નાખ્યો",
    "records.deleteFailed": "કાઢી નાખવું નિષ્ફળ",
    "products.title": "ઉત્પાદનો",
    "products.subtitle": "તમારી ઉત્પાદન ઇન્વેન્ટરી અને શ્રેણીઓ સંચાલિત કરો",
    "products.import": "આયાત",
    "products.export": "નિકાસ",
    "products.addProduct": "ઉત્પાદન ઉમેરો",
    "products.allCategories": "બધી શ્રેણીઓ",
    "products.inStock": "સ્ટોકમાં",
    "products.lowStock": "ઓછો સ્ટોક",
    "products.outOfStock": "સ્ટોક નથી",
    "products.tableTitle": "ઉત્પાદન ઇન્વેન્ટરી અને આગાહી",
    "products.tableSubtitle": "આગામી 30 દિવસ માટે AI માંગ આગાહી",
    "products.product": "ઉત્પાદન",
    "products.category": "શ્રેણી",
    "products.currentStock": "વર્તમાન સ્ટોક",
    "products.predictedDemand": "અંદાજિત માંગ",
    "products.trend": "વલણ",
    "products.confidence": "વિશ્વાસ",
    "products.status": "સ્થિતિ",
    "products.restockNow": "હવે રિસ્ટોક",
    "products.optimal": "શ્રેષ્ઠ",
    "products.overstock": "વધારે સ્ટોક",
    "products.noProducts": "આ ફિલ્ટરમાં કોઈ ઉત્પાદન નથી",
    "insights.title": "AI આંતરદૃષ્ટિ",
    "insights.viewAll": "બધી આંતરદૃષ્ટિ જુઓ",
    "insights.stockAlert": "સ્ટોક ચેતવણી",
    "insights.stockAlertDesc": "ચોખા 5 કિલો થેલા 3 દિવસમાં ખતમ થશે એવી આગાહી. 40+ એકમ રિસ્ટોક કરો.",
    "insights.demandSurge": "માંગ વધારો",
    "insights.demandSurgeDesc": "ઓર્ગેનિક દૂધની માંગ ગયા મહિના કરતાં 23% વધુ. ઓર્ડર વધારો.",
    "insights.overstockAlert": "વધારે સ્ટોક ચેતવણી",
    "insights.overstockAlertDesc": "ખાંડની ઇન્વેન્ટરી અંદાજિત માંગ કરતાં વધુ. પ્રમોશનલ ભાવ વિચારો.",
    "chart.title": "વેચાણ અને માંગ આગાહી",
    "chart.subtitle": "ML આગાહીઓ સાથે ઐતિહાસિક ડેટા",
    "chart.actualSales": "વાસ્તવિક વેચાણ",
    "chart.predictedDemand": "અંદાજિત માંગ",
    "stores.title": "સ્ટોર નેટવર્ક",
    "stores.subtitle": "તમારા વિસ્તારની દુકાનો સાથે જોડાઓ (~5 કિમી)",
    "stores.map": "નકશો",
    "stores.list": "યાદી",
    "stores.registeredStores": "નોંધાયેલ સ્ટોર",
    "stores.citiesCovered": "આવરી લેવાયેલ શહેરો",
    "stores.networkRadius": "નેટવર્ક ત્રિજ્યા",
    "stores.storeLocations": "સ્ટોર સ્થાનો",
    "stores.nearbyStores": "નજીકના સ્ટોર",
    "forecasts.title": "માંગ આગાહીઓ",
    "forecasts.subtitle": "ઇન્વેન્ટરી આયોજન માટે AI આગાહીઓ",
    "forecasts.last30": "છેલ્લા 30 દિવસ",
    "forecasts.runNew": "નવી આગાહી",
    "forecasts.7day": "7 દિવસ આગાહી",
    "forecasts.30day": "30 દિવસ આગાહી",
    "forecasts.accuracyRate": "ચોકસાઈ દર",
    "forecasts.nextRestock": "આગામી રિસ્ટોક",
    "forecasts.exportTitle": "આગાહી ડેટા નિકાસ",
    "forecasts.exportDesc": "વિગતવાર આગાહી અહેવાલો ડાઉનલોડ કરો.",
    "forecasts.exportReport": "અહેવાલ નિકાસ",
    "forecast.dialogTitle": "માંગ આગાહી ચલાવો",
    "forecast.dialogDesc": "તમારી ઇન્વેન્ટરી માટે ML આગાહીઓ બનાવો",
    "forecast.complete": "આગાહી પૂર્ણ!",
    "forecast.updated": "આગાહીઓ અપડેટ થઈ",
    "forecast.params": "આગાહી પરિમાણો",
    "forecast.horizon": "આગાહી સમયગાળો: 30 દિવસ",
    "forecast.model": "મોડેલ: ટાઇમ સિરીઝ ML",
    "forecast.dataPoints": "ડેટા પોઇન્ટ: 180 દિવસ ઇતિહાસ",
    "forecast.allProducts": "ઉત્પાદનો: બધી ઇન્વેન્ટરી",
    "forecast.cancel": "રદ કરો",
    "forecast.start": "આગાહી શરૂ કરો",
    "forecast.loading": "ઐતિહાસિક ડેટા લોડ થઈ રહ્યો છે...",
    "forecast.preprocessing": "ડેટા પ્રીપ્રોસેસિંગ...",
    "forecast.training": "ML મોડેલ તાલીમ...",
    "forecast.generating": "આગાહીઓ બનાવવામાં આવી રહી છે...",
    "forecast.finalizing": "આગાહી અંતિમ રૂપ આપવામાં આવી રહી છે...",
    "forecast.completeToast": "આગાહી પૂર્ણ",
    "forecast.completeDesc": "માંગ આગાહીઓ સફળતાપૂર્વક અપડેટ!",
    "export.title": "અહેવાલ નિકાસ",
    "export.desc": "તમારો માંગ આગાહી અહેવાલ ડાઉનલોડ કરો",
    "export.complete": "નિકાસ પૂર્ણ!",
    "export.checkDownloads": "તમારું ડાઉનલોડ ફોલ્ડર તપાસો",
    "export.summary": "કાર્યકારી સારાંશ",
    "export.summaryDesc": "મુખ્ય મેટ્રિક્સ અને આંતરદૃષ્ટિનો ઝાંખી",
    "export.detailed": "વિગતવાર વિશ્લેષણ",
    "export.detailedDesc": "ઉત્પાદન સ્તર આગાહીઓ સાથે પૂર્ણ વિશ્લેષણ",
    "export.raw": "કાચો ડેટા નિકાસ",
    "export.rawDesc": "સ્પ્રેડશીટમાં વિશ્લેષણ માટે CSV નિકાસ",
    "export.cancel": "રદ કરો",
    "export.export": "અહેવાલ નિકાસ",
    "export.exporting": "નિકાસ થઈ રહી છે...",
    "export.exported": "અહેવાલ નિકાસ થયો",
    "export.exportedDesc": "તમારો અહેવાલ સફળતાપૂર્વક ડાઉનલોડ થયો!",
    "reports.title": "અહેવાલો",
    "reports.subtitle": "વ્યાપાર અહેવાલો બનાવો અને ડાઉનલોડ કરો",
    "reports.schedule": "અહેવાલ શેડ્યૂલ",
    "reports.generate": "અહેવાલ બનાવો",
    "reports.available": "ઉપલબ્ધ અહેવાલો",
    "reports.salesPerf": "વેચાણ પ્રદર્શન",
    "reports.salesPerfDesc": "દૈનિક, સાપ્તાહિક અને માસિક વેચાણ વિશ્લેષણ",
    "reports.inventoryStatus": "ઇન્વેન્ટરી સ્થિતિ",
    "reports.inventoryStatusDesc": "વર્તમાન સ્ટોક સ્તરો અને રિઓર્ડર પોઇન્ટ",
    "reports.demandForecast": "માંગ આગાહી",
    "reports.demandForecastDesc": "આગામી 7-30 દિવસ માટે AI આગાહીઓ",
    "reports.financial": "નાણાકીય સારાંશ",
    "reports.financialDesc": "આવક, ખર્ચ અને નફા માર્જિન",
    "reports.recent": "તાજેતરના અહેવાલો",
    "reports.recentDesc": "અગાઉ બનાવેલ અહેવાલો",
    "notifs.title": "સૂચનાઓ",
    "notifs.subtitle": "ચેતવણીઓ અને આંતરદૃષ્ટિ સાથે અપડેટ રહો",
    "notifs.markAllRead": "બધું વાંચેલ ચિહ્નિત કરો",
    "notifs.empty": "હજુ સુધી કોઈ સૂચનાઓ નથી",
    "notifs.lowStock": "ઓછો સ્ટોક ચેતવણી",
    "notifs.lowStockMsg": "ચોખા 5 કિલો થેલો ઓછો થઈ રહ્યો છે. વર્તમાન સ્ટોક: 30 એકમ.",
    "notifs.forecastUpdated": "આગાહી અપડેટ",
    "notifs.forecastUpdatedMsg": "સાપ્તાહિક માંગ આગાહી 94.2% ચોકસાઈ સાથે અપડેટ થઈ.",
    "notifs.newStore": "નવી દુકાન નોંધણી",
    "notifs.newStoreMsg": "કૃષ્ણા ગ્રોસરીઝ તમારા નેટવર્કમાં જોડાયું.",
    "notifs.salesMilestone": "વેચાણ સીમાચિહ્ન",
    "notifs.salesMilestoneMsg": "અભિનંદન! માસિક વેચાણ ₹60,000 વટાવ્યું.",
    "notifs.demandSurge": "માંગ વધારો",
    "notifs.demandSurgeMsg": "ઓર્ગેનિક દૂધની માંગ સામાન્ય કરતાં 23% વધુ.",
    "notifs.minAgo": "5 મિનિટ પહેલાં",
    "notifs.hourAgo": "1 કલાક પહેલાં",
    "notifs.hoursAgo": "2 કલાક પહેલાં",
    "notifs.dayAgo": "1 દિવસ પહેલાં",
    "notifs.daysAgo": "2 દિવસ પહેલાં",
    "settings.title": "સેટિંગ્સ",
    "settings.subtitle": "તમારું ખાતું અને પસંદગીઓ સંચાલિત કરો",
    "settings.profile": "પ્રોફાઇલ",
    "settings.appearance": "દેખાવ",
    "settings.darkMode": "ડાર્ક મોડ",
    "settings.darkModeDesc": "ડાર્ક થીમ પર સ્વિચ કરો",
    "settings.notifications": "સૂચનાઓ",
    "settings.pushNotifs": "પુશ સૂચનાઓ",
    "settings.pushNotifsDesc": "બ્રાઉઝર સૂચનાઓ મેળવો",
    "settings.emailAlerts": "ઈમેઇલ ચેતવણી",
    "settings.emailAlertsDesc": "દૈનિક સારાંશ ઈમેઇલ",
    "settings.stockAlerts": "સ્ટોક ચેતવણી",
    "settings.stockAlertsDesc": "ઓછી ઇન્વેન્ટરી ચેતવણી",
    "settings.forecastUpdates": "આગાહી અપડેટ",
    "settings.forecastUpdatesDesc": "નવી આગાહી સૂચનાઓ",
    "settings.privacy": "ગોપનીયતા અને સુરક્ષા",
    "settings.help": "મદદ અને સહાય",
    "settings.logout": "લૉગ આઉટ",
    "settings.language": "ભાષા",
    "settings.languageDesc": "તમારી પસંદગીની ભાષા પસંદ કરો",
    "footer.tagline": "ForecastPro — છૂટક માટે બુદ્ધિશાળી માંગ આગાહી",
    "footer.powered": "મશીન લર્નિંગ દ્વારા સંચાલિત",
    "common.storeOwner": "દુકાન માલિક",
    "common.something_wrong": "કંઈક ખોટું થયું.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("app-language");
    return (saved && saved in languageNames ? saved : "en") as Language;
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("app-language", lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
