import { useState } from "react";
import { Download, FileText, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { Label } from "@/components/ui/label";
import { toast } from "@/hooks/use-toast";

interface ExportReportDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

const ExportReportDialog = ({ open, onOpenChange }: ExportReportDialogProps) => {
  const [reportType, setReportType] = useState("summary");
  const [isExporting, setIsExporting] = useState(false);
  const [isComplete, setIsComplete] = useState(false);

  const handleExport = async () => {
    setIsExporting(true);
    await new Promise(resolve => setTimeout(resolve, 1500));
    setIsExporting(false);
    setIsComplete(true);

    // Create a sample report download
    const reportContent = `ForecastPro Report - ${new Date().toLocaleDateString()}
    
Report Type: ${reportType === "summary" ? "Executive Summary" : reportType === "detailed" ? "Detailed Analysis" : "Raw Data Export"}

Key Metrics:
- Total Products: 248
- Monthly Sales: $62,400
- Forecast Accuracy: 94.2%
- Low Stock Alerts: 6

Top Predictions:
1. Rice 5kg - Expected demand increase of 15%
2. Organic Milk - High demand trend continuing
3. Sugar 1kg - Overstock situation detected

Generated by ForecastPro ML Engine`;

    const blob = new Blob([reportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `forecastpro-report-${Date.now()}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Report Exported",
      description: "Your report has been downloaded successfully!",
    });

    setTimeout(() => {
      setIsComplete(false);
      onOpenChange(false);
    }, 1500);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <FileText className="h-5 w-5 text-primary" />
            Export Report
          </DialogTitle>
          <DialogDescription>
            Download your demand forecast report
          </DialogDescription>
        </DialogHeader>

        {isComplete ? (
          <div className="flex flex-col items-center justify-center py-8">
            <div className="h-16 w-16 rounded-full bg-accent/20 flex items-center justify-center mb-4">
              <CheckCircle className="h-8 w-8 text-accent" />
            </div>
            <h3 className="text-lg font-semibold text-foreground">Export Complete!</h3>
            <p className="text-muted-foreground text-sm">Check your downloads folder</p>
          </div>
        ) : (
          <div className="space-y-4">
            <RadioGroup value={reportType} onValueChange={setReportType}>
              <div className="flex items-start space-x-3 p-3 rounded-lg hover:bg-muted/50 transition-colors">
                <RadioGroupItem value="summary" id="summary" />
                <div className="flex-1">
                  <Label htmlFor="summary" className="font-medium cursor-pointer">
                    Executive Summary
                  </Label>
                  <p className="text-xs text-muted-foreground">
                    High-level overview with key metrics and insights
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-3 p-3 rounded-lg hover:bg-muted/50 transition-colors">
                <RadioGroupItem value="detailed" id="detailed" />
                <div className="flex-1">
                  <Label htmlFor="detailed" className="font-medium cursor-pointer">
                    Detailed Analysis
                  </Label>
                  <p className="text-xs text-muted-foreground">
                    Complete breakdown with product-level predictions
                  </p>
                </div>
              </div>

              <div className="flex items-start space-x-3 p-3 rounded-lg hover:bg-muted/50 transition-colors">
                <RadioGroupItem value="raw" id="raw" />
                <div className="flex-1">
                  <Label htmlFor="raw" className="font-medium cursor-pointer">
                    Raw Data Export
                  </Label>
                  <p className="text-xs text-muted-foreground">
                    CSV export for further analysis in spreadsheets
                  </p>
                </div>
              </div>
            </RadioGroup>

            <div className="flex justify-end gap-2 pt-4 border-t">
              <Button variant="outline" onClick={() => onOpenChange(false)}>
                Cancel
              </Button>
              <Button variant="gradient" onClick={handleExport} disabled={isExporting}>
                {isExporting ? (
                  "Exporting..."
                ) : (
                  <>
                    <Download className="h-4 w-4" />
                    Export Report
                  </>
                )}
              </Button>
            </div>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
};

export default ExportReportDialog;
